"""
Einmaliges Seed-Skript: uebertraegt die 52 bisher hart in translations.js
kodierten Textstellen von index.html (data-i18n / data-i18n-html) als
ContentBlock-Zeilen in die DB, damit sie ueber /admin/inhalte editierbar
werden. Schluessel-Konvention: "index_<key>" (Praefix pro Seite, siehe
api_content_bulk() in app.py).

Aufruf: python seed_content_index.py
Sicher mehrfach ausfuehrbar -- ueberspringt bereits vorhandene
schluessel+sprache-Kombinationen, ueberschreibt nichts (falls ein Editor
den Text im Admin-Panel bereits angepasst hat).
"""
from app import app
from extensions import db
from models import ContentBlock

SEED_DATA = {
    "de": {
        "nav_warum": "Warum",
        "nav_mitmachen": "Mitmachen",
        "nav_spenden": "Unterstützen",
        "nav_anmelden": "Anmelden",
        "nav_ueber": "Über",
        "nav_foerderer": "Förderer",
        "nav_quellen": "Quellen",
        "nav_news": "News",
        "nav_leihgeraete": "Leihgerät",
        "nav_menu": "Menü",
        "btn_leihgeraet": "⬡ BioComm-Knoten leihen",
        "btn_fragen": "⬤ Offene Fragen?",
        "btn_join": "Jetzt mitmachen",
        "btn_support": "Projekt unterstützen",
        "btn_contact": "Kontakt",
        "btn_register": "Jetzt registrieren",
        "hero_sub": "Ein weltweites Citizen-Science-Netzwerk zur Erfassung bioelektrischer Signale aus Mykorrhiza- und Pilznetzwerken. Die Signale existieren — die Frage ist, was sie bedeuten.",
        "live_badge": "aktiver Knoten — werde der nächste",
        "player_hint": "Genieße die Musik während du den weiteren Inhalt durchforstest.",
        "label_vision": "Die größere Frage",
        "label_warum": "Das Warum",
        "label_mitmachen": "So funktioniert es",
        "label_daten": "Transparenz",
        "label_spenden": "Unterstützung",
        "label_ueber": "Das Projekt",
        "h2_vision": "Was möglich wird, wenn wir <em>verstehen</em>",
        "h2_warum": "Ein Netzwerk das<br><em>zuhört</em>",
        "h2_mitmachen": "In vier Schritten<br>zum eigenen <em>Knoten</em>",
        "h2_daten": "Wie deine Daten<br><em>fließen</em>",
        "h2_spenden": "Das Projekt<br><em>unterstützen</em>",
        "h2_ueber": "Unabhängige Wissenschaft<br>von <em>unten</em>",
        "vision_p1": "Unter unseren Füßen liegt das älteste und weitreichendste Kommunikationsnetzwerk der Erde. Mykorrhiza-Pilze verbinden seit 400 Millionen Jahren nahezu alle Landpflanzen miteinander — sie transportieren Nährstoffe, übermitteln Warnsignale und koordinieren das Leben im Boden auf eine Weise die wir gerade erst zu verstehen beginnen. Sie senden elektrische Signale. Messbar. Reproduzierbar. Und bisher kaum entschlüsselt.",
        "vision_p2": "OpenMycoNet stellt die einfache aber weitreichende Frage: Was passiert wenn wir aufhören, Böden nur von außen zu analysieren — und stattdessen anfangen zuzuhören was das Netzwerk selbst sendet? Was wenn die Pflanze uns längst sagt dass sie Durst hat, bevor wir es sehen? Was wenn der Boden selbst meldet dass ein Schädling naht, bevor der erste Schaden entsteht?",
        "vision_p3": "Das sind keine spekulativen Fragen. Die wissenschaftliche Grundlage existiert. Was fehlt sind Daten — viele, aus verschiedenen Klimazonen, Substraten, Jahreszeiten. Genau das kann kein einzelnes Labor liefern. Aber eine weltweite Gemeinschaft von Menschen die in ihrem Garten, ihrem Wald, ihrem Gewächshaus messen — schon.",
        "vision_quote": "Das Netzwerk sendet. Wir haben gerade erst angefangen zuzuhören.",
        "vision_closing": "Jeder BioComm-Knoten der weltweit in Betrieb geht bringt uns einen Schritt näher an das Verständnis — für alle.",
        "desc_warum": "Mykorrhiza-Pilze verbinden über 90 % aller Landpflanzen. Sie senden elektrische Signale — messbar, reproduzierbar, rätselhaft. Gemeinsam können wir verstehen was sie bedeuten.",
        "desc_mitmachen": "Die Ergebnisse und Daten des Netzwerks stehen allen offen — auch ohne eigenen Knoten. Wer selbst einen BioComm-Knoten betreiben möchte, bewirbt sich unten für einen der kuratierten Plätze.",
        "desc_daten": "GPS-Koordinaten werden auf 10×10 km vergröbert — kein exakter Standort. Keine personenbezogenen Daten. Alle Rohdaten öffentlich zugänglich.",
        "donate_p": "OpenMycoNet ist ein unabhängiges Citizen-Science-Projekt ohne institutionelle Förderung. Serverkosten und Weiterentwicklung werden durch freiwillige Spenden finanziert. Jeder Betrag hilft.",
        "donate_note": "Du kannst auch spenden ohne Dich registrieren zu müssen, aber wir würden uns freuen wenn Du es dennoch machst und so ein Teil des Netzwerks wirst.",
        "donate_claim": "Wir für OpenMycoNet — OpenMycoNet für alle.",
        "donate_fee_label": "Transaktionskosten übernehmen",
        "buch_label": "Gratisdownload",
        "buch_desc": "Eine Geschichte über die Symbiose der dritten Art",
        "buch_btn": "↓ Roman herunterladen",
        "buch_note": "PDF · kostenlos · Robert Jank · 2026",
        "buch_teaser_label": "✦ Kostenloser Download ✦",
        "buch_teaser_text": "„Das letzte Korn\" — ein Roman über Menschen, Mykorrhiza, KI und die Frage, wem die Natur gehört und wie man mit ihr leben könnte.",
        "about_p1": "OpenMycoNet wurde von Robert Jank, unabhängigem Erfinder aus Maintal bei Frankfurt, initiiert — ohne Institutszugehörigkeit, mit dem Ziel zu verstehen was Mykorrhiza-Netzwerke elektrisch signalisieren.",
        "about_p2": "Das zugrundeliegende System BioComm ist durch ein Gebrauchsmuster beim DPMA geschützt. Die Software wird als portable .exe bereitgestellt. Die Messdaten gehören der Gemeinschaft.",
        "about_p3": "Prinzip: Proprietary Intelligence, Open Data — das KI-Modell ist geschützt, die Daten die es trainieren sind frei."
    },
    "en": {
        "nav_warum": "Why",
        "nav_mitmachen": "Join",
        "nav_spenden": "Support",
        "nav_anmelden": "Register",
        "nav_ueber": "About",
        "nav_foerderer": "Supporters",
        "nav_quellen": "References",
        "nav_news": "News",
        "nav_leihgeraete": "Loan Device",
        "nav_menu": "Menu",
        "btn_leihgeraet": "⬡ Borrow BioComm Node",
        "btn_fragen": "⬤ Open Questions?",
        "btn_join": "Join now",
        "btn_support": "Support the project",
        "btn_contact": "Contact",
        "btn_register": "Register now",
        "hero_sub": "A global citizen science network recording bioelectrical signals from mycorrhizal and fungal networks. The signals exist — the question is what they mean.",
        "live_badge": "active node — be the next",
        "player_hint": "Enjoy the music while exploring the rest of the content.",
        "label_vision": "The bigger question",
        "label_warum": "The Why",
        "label_mitmachen": "How it works",
        "label_daten": "Transparency",
        "label_spenden": "Support",
        "label_ueber": "The project",
        "h2_vision": "What becomes possible when we <em>understand</em>",
        "h2_warum": "A network that<br><em>listens</em>",
        "h2_mitmachen": "Your own node<br>in four <em>steps</em>",
        "h2_daten": "How your data<br><em>flows</em>",
        "h2_spenden": "Support<br>the <em>project</em>",
        "h2_ueber": "Independent science<br>from <em>below</em>",
        "vision_p1": "Beneath our feet lies the oldest and most extensive communication network on Earth. Mycorrhizal fungi have connected almost all land plants for 400 million years — transporting nutrients, transmitting warning signals, and coordinating life in the soil in ways we are only beginning to understand. They send electrical signals. Measurable. Reproducible. And barely deciphered so far.",
        "vision_p2": "OpenMycoNet asks a simple yet profound question: what happens when we stop analysing soil only from the outside — and start listening to what the network itself is sending? What if the plant has long been telling us it's thirsty, before we can even see it? What if the soil itself signals the approach of a pest, before the first damage appears?",
        "vision_p3": "These are not speculative questions. The scientific foundation exists. What is missing is data — lots of it, from different climate zones, substrates, seasons. No single laboratory can provide that. But a global community of people measuring in their gardens, their forests, their greenhouses — can.",
        "vision_quote": "The network is transmitting. We have only just begun to listen.",
        "vision_closing": "Every BioComm node that goes live anywhere in the world brings us one step closer to understanding — for everyone.",
        "desc_warum": "Mycorrhizal fungi connect over 90% of all land plants. They send electrical signals — measurable, reproducible, enigmatic. Together we can understand what they mean.",
        "desc_mitmachen": "The network's results and data are open to everyone — even without operating your own node. If you'd like to run a BioComm node yourself, apply below for one of the curated spots.",
        "desc_daten": "GPS coordinates are coarsened to 10×10 km — no exact location. No personal data. All raw data publicly accessible.",
        "donate_p": "OpenMycoNet is an independent citizen science project without institutional funding. Server costs and further development are financed by voluntary donations. Every contribution helps.",
        "donate_note": "You can donate without registering, but we would be delighted if you did and became part of the network.",
        "donate_claim": "We support OpenMycoNet — OpenMycoNet supports everyone.",
        "donate_fee_label": "Cover transaction fees",
        "buch_label": "Free Download",
        "buch_desc": "A story about the symbiosis of the third kind",
        "buch_btn": "↓ Download novel",
        "buch_note": "PDF · free · Robert Jank · 2026",
        "buch_teaser_label": "✦ Free Download ✦",
        "buch_teaser_text": "\"Das letzte Korn\" — a novel about people, mycorrhiza, AI and the question of who owns nature and how we might live with it.",
        "about_p1": "OpenMycoNet was initiated by Robert Jank, independent inventor from Maintal near Frankfurt — without institutional affiliation, with the goal of understanding what mycorrhizal networks signal electrically.",
        "about_p2": "The underlying BioComm system is protected by a utility model registered with the DPMA. The software is provided as a portable .exe. The measurement data belongs to the community.",
        "about_p3": "Principle: Proprietary Intelligence, Open Data — the AI model is protected, the data that trains it is free."
    },
    "nl": {
        "nav_warum": "Waarom",
        "nav_mitmachen": "Meedoen",
        "nav_spenden": "Ondersteunen",
        "nav_anmelden": "Aanmelden",
        "nav_ueber": "Over",
        "nav_foerderer": "Partners",
        "nav_quellen": "Bronnen",
        "nav_news": "Nieuws",
        "nav_leihgeraete": "Leentoestel",
        "nav_menu": "Menu",
        "btn_leihgeraet": "⬡ BioComm-knoop lenen",
        "btn_fragen": "⬤ Vragen?",
        "btn_join": "Nu meedoen",
        "btn_support": "Project ondersteunen",
        "btn_contact": "Contact",
        "btn_register": "Nu aanmelden",
        "hero_sub": "Een wereldwijd citizen science-netwerk voor het meten van bio-elektrische signalen uit mycorrhiza- en schimmelnetwerken. De signalen bestaan — de vraag is wat ze betekenen.",
        "live_badge": "actief knooppunt — word de volgende",
        "player_hint": "Geniet van de muziek terwijl je de rest van de inhoud verkent.",
        "label_vision": "De grotere vraag",
        "label_warum": "Het Waarom",
        "label_mitmachen": "Zo werkt het",
        "label_daten": "Transparantie",
        "label_spenden": "Ondersteuning",
        "label_ueber": "Het project",
        "h2_vision": "Wat mogelijk wordt als we <em>begrijpen</em>",
        "h2_warum": "Een netwerk dat<br><em>luistert</em>",
        "h2_mitmachen": "Jouw eigen knooppunt<br>in vier <em>stappen</em>",
        "h2_daten": "Hoe jouw data<br><em>stroomt</em>",
        "h2_spenden": "Het project<br><em>ondersteunen</em>",
        "h2_ueber": "Onafhankelijke wetenschap<br>van <em>onderaf</em>",
        "vision_p1": "Onder onze voeten ligt het oudste en meest uitgebreide communicatienetwerk van de aarde. Mycorrhizaschimmels verbinden al 400 miljoen jaar vrijwel alle landplanten met elkaar — ze transporteren voedingsstoffen, sturen waarschuwingssignalen en coördineren het leven in de bodem op een manier die we nog maar nauwelijks beginnen te begrijpen. Ze zenden elektrische signalen. Meetbaar. Reproduceerbaar. En tot nu toe nauwelijks ontcijferd.",
        "vision_p2": "OpenMycoNet stelt een eenvoudige maar verstrekkende vraag: wat gebeurt er als we ophouden bodems alleen van buitenaf te analyseren — en in plaats daarvan beginnen te luisteren naar wat het netwerk zelf uitzendt? Wat als de plant ons al lang vertelt dat ze dorst heeft, voordat we het kunnen zien? Wat als de bodem zelf aangeeft dat er een plaag nadert, voordat de eerste schade ontstaat?",
        "vision_p3": "Dit zijn geen speculatieve vragen. De wetenschappelijke basis bestaat. Wat ontbreekt zijn gegevens — veel gegevens, uit verschillende klimaatzones, substraten, seizoenen. Dat kan geen enkel laboratorium leveren. Maar een wereldwijde gemeenschap van mensen die meten in hun tuin, hun bos, hun kas — wel.",
        "vision_quote": "Het netwerk zendt. We zijn er nog maar net mee begonnen te luisteren.",
        "vision_closing": "Elk BioComm-knooppunt dat wereldwijd in gebruik wordt genomen brengt ons een stap dichter bij begrip — voor iedereen.",
        "desc_warum": "Mycorrhizaschimmels verbinden meer dan 90% van alle landplanten. Ze zenden elektrische signalen — meetbaar, reproduceerbaar, raadselachtig. Samen kunnen we begrijpen wat ze betekenen.",
        "desc_mitmachen": "De resultaten en gegevens van het netwerk zijn voor iedereen toegankelijk — ook zonder eigen node. Wie zelf een BioComm-node wil beheren, solliciteert hieronder voor een van de gecureerde plekken.",
        "desc_daten": "GPS-coördinaten worden vergroot naar 10×10 km — geen exacte locatie. Geen persoonsgegevens. Alle ruwe data openbaar toegankelijk.",
        "donate_p": "OpenMycoNet is een onafhankelijk citizen science-project zonder institutionele financiering. Serverkosten en verdere ontwikkeling worden gefinancierd door vrijwillige donaties. Elk bedrag helpt.",
        "donate_note": "Je kunt doneren zonder je te registreren, maar we zouden het fijn vinden als je dat toch deed en zo deel uitmaakt van het netwerk.",
        "donate_claim": "Wij voor OpenMycoNet — OpenMycoNet voor iedereen.",
        "donate_fee_label": "Transactiekosten dekken",
        "buch_label": "Gratis download",
        "buch_desc": "Een verhaal over de symbiose van de derde soort",
        "buch_btn": "↓ Roman downloaden",
        "buch_note": "PDF · gratis · Robert Jank · 2026",
        "buch_teaser_label": "✦ Gratis Download ✦",
        "buch_teaser_text": "\"Das letzte Korn\" — een roman over mensen, mycorrhiza, AI en de vraag aan wie de natuur toebehoort en hoe we ermee zouden kunnen leven.",
        "about_p1": "OpenMycoNet werd geïnitieerd door Robert Jank, onafhankelijk uitvinder uit Maintal bij Frankfurt — zonder institutionele binding, met als doel te begrijpen wat mycorrhizanetwerken elektrisch signaleren.",
        "about_p2": "Het onderliggende BioComm-systeem is beschermd door een gebruiksmodel geregistreerd bij het DPMA. De software wordt aangeboden als draagbare .exe. De meetgegevens zijn eigendom van de gemeenschap.",
        "about_p3": "Principe: Proprietary Intelligence, Open Data — het AI-model is beschermd, de data die het traint zijn vrij."
    },
    "fr": {
        "nav_warum": "Pourquoi",
        "nav_mitmachen": "Participer",
        "nav_spenden": "Soutenir",
        "nav_anmelden": "S'inscrire",
        "nav_ueber": "À propos",
        "nav_foerderer": "Partenaires",
        "nav_quellen": "Sources",
        "nav_news": "Actualités",
        "nav_leihgeraete": "Appareil en prêt",
        "nav_menu": "Menu",
        "btn_leihgeraet": "⬡ Emprunter un nœud BioComm",
        "btn_fragen": "⬤ Des questions?",
        "btn_join": "Rejoindre",
        "btn_support": "Soutenir le projet",
        "btn_contact": "Contact",
        "btn_register": "S'inscrire maintenant",
        "hero_sub": "Un réseau mondial de science citoyenne qui enregistre les signaux bioélectriques des réseaux mycorhiziens et fongiques. Les signaux existent — la question est ce qu'ils signifient.",
        "live_badge": "nœud actif — soyez le prochain",
        "player_hint": "Profitez de la musique pendant que vous explorez le reste du contenu.",
        "label_vision": "La grande question",
        "label_warum": "Le Pourquoi",
        "label_mitmachen": "Comment ça fonctionne",
        "label_daten": "Transparence",
        "label_spenden": "Soutien",
        "label_ueber": "Le projet",
        "h2_vision": "Ce qui devient possible quand nous <em>comprenons</em>",
        "h2_warum": "Un réseau qui<br><em>écoute</em>",
        "h2_mitmachen": "Votre propre nœud<br>en quatre <em>étapes</em>",
        "h2_daten": "Comment vos données<br><em>circulent</em>",
        "h2_spenden": "Soutenir<br>le <em>projet</em>",
        "h2_ueber": "Une science indépendante<br>venue d'<em>en bas</em>",
        "vision_p1": "Sous nos pieds se trouve le réseau de communication le plus ancien et le plus étendu de la Terre. Les champignons mycorhiziens relient presque toutes les plantes terrestres depuis 400 millions d'années — ils transportent des nutriments, transmettent des signaux d'alerte et coordonnent la vie dans le sol d'une manière que nous commençons à peine à comprendre. Ils émettent des signaux électriques. Mesurables. Reproductibles. Et à peine déchiffrés jusqu'ici.",
        "vision_p2": "OpenMycoNet pose une question simple mais fondamentale : que se passe-t-il si nous cessons d'analyser les sols uniquement de l'extérieur — et commençons à écouter ce que le réseau lui-même émet ? Et si la plante nous disait depuis longtemps qu'elle a soif, avant même que nous le voyions ? Et si le sol signalait lui-même l'approche d'un ravageur, avant que les premiers dégâts n'apparaissent ?",
        "vision_p3": "Ce ne sont pas des questions spéculatives. La base scientifique existe. Ce qui manque, ce sont des données — beaucoup, provenant de différentes zones climatiques, substrats, saisons. Aucun laboratoire ne peut fournir cela seul. Mais une communauté mondiale de personnes mesurant dans leur jardin, leur forêt, leur serre — si.",
        "vision_quote": "Le réseau émet. Nous venons tout juste de commencer à écouter.",
        "vision_closing": "Chaque nœud BioComm mis en service dans le monde nous rapproche d'un pas de la compréhension — pour tous.",
        "desc_warum": "Les champignons mycorhiziens connectent plus de 90 % de toutes les plantes terrestres. Ils émettent des signaux électriques — mesurables, reproductibles, énigmatiques. Ensemble, nous pouvons comprendre ce qu'ils signifient.",
        "desc_mitmachen": "Les résultats et données du réseau sont accessibles à tous — même sans exploiter son propre nœud. Si vous souhaitez exploiter vous-même un nœud BioComm, postulez ci-dessous pour l'une des places sélectionnées.",
        "desc_daten": "Les coordonnées GPS sont arrondies à 10×10 km — aucune localisation précise. Aucune donnée personnelle. Toutes les données brutes accessibles publiquement.",
        "donate_p": "OpenMycoNet est un projet de science citoyenne indépendant sans financement institutionnel. Les coûts de serveur et le développement ultérieur sont financés par des dons volontaires. Chaque contribution compte.",
        "donate_note": "Vous pouvez faire un don sans vous inscrire, mais nous serions ravis que vous le fassiez quand même et deveniez ainsi membre du réseau.",
        "donate_claim": "Nous pour OpenMycoNet — OpenMycoNet pour tous.",
        "donate_fee_label": "Couvrir les frais de transaction",
        "buch_label": "Téléchargement gratuit",
        "buch_desc": "Une histoire sur la symbiose du troisième type",
        "buch_btn": "↓ Télécharger le roman",
        "buch_note": "PDF · gratuit · Robert Jank · 2026",
        "buch_teaser_label": "✦ Téléchargement Gratuit ✦",
        "buch_teaser_text": "\"Das letzte Korn\" — un roman sur des hommes, les mycorhizes, l'IA et la question de qui appartient la nature et comment y vivre.",
        "about_p1": "OpenMycoNet a été initié par Robert Jank, inventeur indépendant de Maintal près de Francfort — sans appartenance institutionnelle, avec l'objectif de comprendre ce que les réseaux mycorhiziens signalent électriquement.",
        "about_p2": "Le système BioComm sous-jacent est protégé par un modèle d'utilité déposé auprès du DPMA. Le logiciel est fourni en tant qu'.exe portable. Les données de mesure appartiennent à la communauté.",
        "about_p3": "Principe : Proprietary Intelligence, Open Data — le modèle d'IA est protégé, les données qui l'entraînent sont libres."
    },
    "es": {
        "nav_warum": "Por qué",
        "nav_mitmachen": "Unirse",
        "nav_spenden": "Apoyar",
        "nav_anmelden": "Registrarse",
        "nav_ueber": "Acerca de",
        "nav_foerderer": "Patrocinadores",
        "nav_quellen": "Fuentes",
        "nav_news": "Noticias",
        "nav_leihgeraete": "Dispositivo en préstamo",
        "nav_menu": "Menú",
        "btn_leihgeraet": "⬡ Pedir prestado un nodo BioComm",
        "btn_fragen": "⬤ ¿Preguntas?",
        "btn_join": "Unirse ahora",
        "btn_support": "Apoyar el proyecto",
        "btn_contact": "Contacto",
        "btn_register": "Registrarse ahora",
        "hero_sub": "Una red mundial de ciencia ciudadana que registra señales bioeléctricas de redes micorrícicas y fúngicas. Las señales existen — la pregunta es qué significan.",
        "live_badge": "nodo activo — sé el siguiente",
        "player_hint": "Disfruta de la música mientras exploras el resto del contenido.",
        "label_vision": "La pregunta mayor",
        "label_warum": "El Por qué",
        "label_mitmachen": "Cómo funciona",
        "label_daten": "Transparencia",
        "label_spenden": "Apoyo",
        "label_ueber": "El proyecto",
        "h2_vision": "Lo que se vuelve posible cuando <em>comprendemos</em>",
        "h2_warum": "Una red que<br><em>escucha</em>",
        "h2_mitmachen": "Tu propio nodo<br>en cuatro <em>pasos</em>",
        "h2_daten": "Cómo fluyen<br>tus <em>datos</em>",
        "h2_spenden": "Apoyar<br>el <em>proyecto</em>",
        "h2_ueber": "Ciencia independiente<br>desde <em>abajo</em>",
        "vision_p1": "Bajo nuestros pies se encuentra la red de comunicación más antigua y extensa de la Tierra. Los hongos micorrícicos llevan 400 millones de años conectando casi todas las plantas terrestres — transportan nutrientes, transmiten señales de advertencia y coordinan la vida en el suelo de maneras que apenas comenzamos a comprender. Emiten señales eléctricas. Medibles. Reproducibles. Y apenas descifradas hasta ahora.",
        "vision_p2": "¿Qué ocurre cuando dejamos de analizar los suelos solo desde el exterior — y empezamos a escuchar lo que la red misma está enviando? ¿Y si la planta lleva tiempo diciéndonos que tiene sed, antes de que podamos verlo? ¿Y si el propio suelo nos avisa de la llegada de una plaga, antes de que aparezca el primer daño?",
        "vision_p3": "No son preguntas especulativas. La base científica existe. Lo que falta son datos — muchos, de diferentes zonas climáticas, sustratos, estaciones. Ningún laboratorio puede proporcionar eso solo. Pero una comunidad mundial de personas que miden en su jardín, su bosque, su invernadero — sí puede.",
        "vision_quote": "La red transmite. Apenas hemos empezado a escuchar.",
        "vision_closing": "Cada nodo BioComm que entra en funcionamiento en cualquier parte del mundo nos acerca un paso más a la comprensión — para todos.",
        "desc_warum": "Los hongos micorrícicos conectan más del 90% de todas las plantas terrestres. Envían señales eléctricas — medibles, reproducibles, enigmáticas. Juntos podemos entender qué significan.",
        "desc_mitmachen": "Los resultados y datos de la red están abiertos a todos — incluso sin operar tu propio nodo. Si quieres operar tú mismo un nodo BioComm, postúlate abajo para una de las plazas seleccionadas.",
        "desc_daten": "Las coordenadas GPS se redondean a 10×10 km — sin ubicación exacta. Sin datos personales. Todos los datos brutos accesibles públicamente.",
        "donate_p": "OpenMycoNet es un proyecto de ciencia ciudadana independiente sin financiación institucional. Los costes de servidor y el desarrollo posterior se financian con donaciones voluntarias. Cada aportación cuenta.",
        "donate_note": "Puedes donar sin registrarte, pero nos alegraría mucho que lo hicieras y así formaras parte de la red.",
        "donate_claim": "Nosotros por OpenMycoNet — OpenMycoNet para todos.",
        "donate_fee_label": "Cubrir los costes de transacción",
        "buch_label": "Descarga gratuita",
        "buch_desc": "Una historia sobre la simbiosis del tercer tipo",
        "buch_btn": "↓ Descargar novela",
        "buch_note": "PDF · gratuito · Robert Jank · 2026",
        "buch_teaser_label": "✦ Descarga Gratuita ✦",
        "buch_teaser_text": "\"Das letzte Korn\" — una novela sobre personas, micorrizas, IA y la pregunta de a quién pertenece la naturaleza y cómo podríamos vivir con ella.",
        "about_p1": "OpenMycoNet fue iniciado por Robert Jank, inventor independiente de Maintal, cerca de Frankfurt — sin afiliación institucional, con el objetivo de comprender qué señalizan eléctricamente las redes micorrícicas.",
        "about_p2": "El sistema BioComm subyacente está protegido por un El sistema BioComm subyacente está protegido por un modelo de utilidad registrado en la DPMA. El software se proporciona como .exe portátil. Los datos de medición pertenecen a la comunidad.",
        "about_p3": "Principio: Proprietary Intelligence, Open Data — el modelo de IA está protegido, los datos que lo entrenan son libres."
    }
}

with app.app_context():
    angelegt = 0
    uebersprungen = 0
    for sprache, werte in SEED_DATA.items():
        for key, inhalt in werte.items():
            schluessel = f'index_{key}'
            existing = ContentBlock.query.filter_by(schluessel=schluessel, sprache=sprache).first()
            if existing:
                uebersprungen += 1
                continue
            db.session.add(ContentBlock(schluessel=schluessel, sprache=sprache, inhalt=inhalt))
            angelegt += 1
    db.session.commit()
    print(f'{angelegt} Content-Bloecke angelegt, {uebersprungen} bereits vorhanden uebersprungen.')
