"""news uebersetzung_gruppe

Revision ID: 26d8c69e1502
Revises: 1e00d5c30c69
Create Date: 2026-09-17 19:11:38.875453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d8c69e1502'
down_revision = '1e00d5c30c69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uebersetzung_gruppe', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_news_uebersetzung_gruppe'), ['uebersetzung_gruppe'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_uebersetzung_gruppe'))
        batch_op.drop_column('uebersetzung_gruppe')

    # ### end Alembic commands ###
