"""bewerbung status_geaendert_am

Zeitpunkt der letzten Statusaenderung (Admin). Ab da laeuft die Loeschfrist
abgelehnter Bewerbungen (omn/aufbewahrung.py, 6 Monate). Kein Backfill:
Alt-Zeilen bleiben NULL, die Frist rechnet dann ab erstellt_am.

Revision ID: 8f545721d47e
Revises: da901ffb142f
Create Date: 2026-09-28 13:33:27.978463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f545721d47e'
down_revision = 'da901ffb142f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bewerbung', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_geaendert_am', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bewerbung', schema=None) as batch_op:
        batch_op.drop_column('status_geaendert_am')

    # ### end Alembic commands ###
