"""baseline: aktuelles Schema

Revision ID: 959850bfc924
Revises: 
Create Date: 2026-09-09 12:28:04.422630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959850bfc924'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('totp_aktiviert', sa.Boolean(), nullable=True),
    sa.Column('totp_recovery', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chat_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=True),
    sa.Column('chunks_used', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_log_erstellt_am'), ['erstellt_am'], unique=False)

    op.create_table('content_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schluessel', sa.String(length=100), nullable=False),
    sa.Column('sprache', sa.String(length=10), nullable=True),
    sa.Column('inhalt', sa.Text(), nullable=False),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schluessel', 'sprache', name='uq_contentblock_key_lang')
    )
    op.create_table('fehlerprotokoll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zeitpunkt', sa.DateTime(), nullable=True),
    sa.Column('pfad', sa.String(length=300), nullable=True),
    sa.Column('methode', sa.String(length=10), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('fehlertyp', sa.String(length=120), nullable=True),
    sa.Column('nachricht', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fehlerprotokoll', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fehlerprotokoll_zeitpunkt'), ['zeitpunkt'], unique=False)

    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=200), nullable=False),
    sa.Column('untertitel', sa.String(length=300), nullable=True),
    sa.Column('inhalt', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=250), nullable=True),
    sa.Column('sprache', sa.String(length=10), nullable=True),
    sa.Column('bild_dateiname', sa.String(length=255), nullable=True),
    sa.Column('veroeffentlicht', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_veroeffentlicht'), ['veroeffentlicht'], unique=False)

    op.create_table('nutzer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('sprache', sa.String(length=10), nullable=True),
    sa.Column('land', sa.String(length=100), nullable=True),
    sa.Column('gruppe', sa.String(length=50), nullable=True),
    sa.Column('bestaetigt', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('registriert_am', sa.DateTime(), nullable=True),
    sa.Column('fachrolle', sa.String(length=30), nullable=True),
    sa.Column('ist_hyphist', sa.Boolean(), nullable=False),
    sa.Column('ist_sporist', sa.Boolean(), nullable=False),
    sa.Column('login_token', sa.String(length=100), nullable=True),
    sa.Column('login_token_angefordert_am', sa.DateTime(), nullable=True),
    sa.Column('keine_mails', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login_token'),
    sa.UniqueConstraint('token')
    )
    op.create_table('presseeintrag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('quelle', sa.String(length=200), nullable=False),
    sa.Column('anreissertext', sa.Text(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=True),
    sa.Column('sprache', sa.String(length=10), nullable=True),
    sa.Column('veroeffentlicht', sa.Boolean(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presseeintrag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presseeintrag_veroeffentlicht'), ['veroeffentlicht'], unique=False)

    op.create_table('pressekandidat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('quelle', sa.String(length=200), nullable=True),
    sa.Column('datum', sa.Date(), nullable=True),
    sa.Column('sprache', sa.String(length=10), nullable=True),
    sa.Column('gefunden_am', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('pressekandidat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pressekandidat_status'), ['status'], unique=False)

    op.create_table('rechnungs_zaehler',
    sa.Column('jahr', sa.Integer(), nullable=False),
    sa.Column('zaehler', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('jahr')
    )
    op.create_table('spende',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ziel_betrag', sa.Float(), nullable=True),
    sa.Column('aktueller_betrag', sa.Float(), nullable=True),
    sa.Column('sichtbar', sa.Boolean(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suchbegriff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sprache', sa.String(length=10), nullable=False),
    sa.Column('begriff', sa.String(length=200), nullable=False),
    sa.Column('quellsprache', sa.String(length=20), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bewerbung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('rolle', sa.String(length=50), nullable=True),
    sa.Column('profession', sa.String(length=200), nullable=True),
    sa.Column('substrat', sa.String(length=200), nullable=True),
    sa.Column('adresse', sa.String(length=300), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('sprache', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('nutzer_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nutzer_id'], ['nutzer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bewerbung', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bewerbung_nutzer_id'), ['nutzer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bewerbung_status'), ['status'], unique=False)

    op.create_table('foerderer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('status_geaendert_am', sa.DateTime(), nullable=True),
    sa.Column('firma', sa.String(length=120), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('kategorie', sa.String(length=80), nullable=True),
    sa.Column('typ', sa.String(length=20), nullable=True),
    sa.Column('gegenleistung_erwartet', sa.Text(), nullable=True),
    sa.Column('ansprechpartner', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('betrag', sa.Float(), nullable=True),
    sa.Column('logo_datei', sa.String(length=255), nullable=True),
    sa.Column('paypal_txn_id', sa.String(length=128), nullable=True),
    sa.Column('rechnung_nr', sa.String(length=32), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktiviert_am', sa.DateTime(), nullable=True),
    sa.Column('laeuft_ab_am', sa.Date(), nullable=True),
    sa.Column('nutzer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nutzer_id'], ['nutzer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('foerderer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_foerderer_nutzer_id'), ['nutzer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_foerderer_status'), ['status'], unique=False)

    op.create_table('knoten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knoten_id', sa.String(length=50), nullable=False),
    sa.Column('nutzer_id', sa.Integer(), nullable=False),
    sa.Column('lat_grob', sa.Float(), nullable=True),
    sa.Column('lon_grob', sa.Float(), nullable=True),
    sa.Column('substrat', sa.String(length=100), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('api_key', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['nutzer_id'], ['nutzer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knoten_id')
    )
    with op.batch_alter_table('knoten', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knoten_api_key'), ['api_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_knoten_nutzer_id'), ['nutzer_id'], unique=False)

    op.create_table('aufgabe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foerderer_id', sa.Integer(), nullable=True),
    sa.Column('knoten_id', sa.Integer(), nullable=True),
    sa.Column('titel', sa.String(length=200), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('erstellt_von', sa.String(length=10), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('erledigt_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['foerderer_id'], ['foerderer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knoten_id'], ['knoten.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aufgabe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aufgabe_foerderer_id'), ['foerderer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aufgabe_knoten_id'), ['knoten_id'], unique=False)

    op.create_table('messung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knoten_id', sa.Integer(), nullable=False),
    sa.Column('zeitstempel', sa.DateTime(), nullable=True),
    sa.Column('kanal', sa.Integer(), nullable=True),
    sa.Column('wert_uv', sa.Float(), nullable=True),
    sa.Column('boden_temp', sa.Float(), nullable=True),
    sa.Column('boden_feuchte', sa.Float(), nullable=True),
    sa.Column('luft_temp', sa.Float(), nullable=True),
    sa.Column('luft_feuchte', sa.Float(), nullable=True),
    sa.Column('licht', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['knoten_id'], ['knoten.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messung', schema=None) as batch_op:
        batch_op.create_index('ix_messung_knoten_zeit', ['knoten_id', 'zeitstempel'], unique=False)

    op.create_table('kommentar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foerderer_id', sa.Integer(), nullable=True),
    sa.Column('knoten_id', sa.Integer(), nullable=True),
    sa.Column('aufgabe_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('autor', sa.String(length=10), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aufgabe_id'], ['aufgabe.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['foerderer_id'], ['foerderer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knoten_id'], ['knoten.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kommentar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kommentar_aufgabe_id'), ['aufgabe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kommentar_foerderer_id'), ['foerderer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kommentar_knoten_id'), ['knoten_id'], unique=False)

    op.create_table('kollaboration_anhang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kommentar_id', sa.Integer(), nullable=False),
    sa.Column('dateiname', sa.String(length=255), nullable=False),
    sa.Column('originalname', sa.String(length=255), nullable=True),
    sa.Column('groesse', sa.Integer(), nullable=True),
    sa.Column('hochgeladen_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kommentar_id'], ['kommentar.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kollaboration_anhang', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kollaboration_anhang_kommentar_id'), ['kommentar_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kollaboration_anhang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kollaboration_anhang_kommentar_id'))

    op.drop_table('kollaboration_anhang')
    with op.batch_alter_table('kommentar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kommentar_knoten_id'))
        batch_op.drop_index(batch_op.f('ix_kommentar_foerderer_id'))
        batch_op.drop_index(batch_op.f('ix_kommentar_aufgabe_id'))

    op.drop_table('kommentar')
    with op.batch_alter_table('messung', schema=None) as batch_op:
        batch_op.drop_index('ix_messung_knoten_zeit')

    op.drop_table('messung')
    with op.batch_alter_table('aufgabe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aufgabe_knoten_id'))
        batch_op.drop_index(batch_op.f('ix_aufgabe_foerderer_id'))

    op.drop_table('aufgabe')
    with op.batch_alter_table('knoten', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knoten_nutzer_id'))
        batch_op.drop_index(batch_op.f('ix_knoten_api_key'))

    op.drop_table('knoten')
    with op.batch_alter_table('foerderer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_foerderer_status'))
        batch_op.drop_index(batch_op.f('ix_foerderer_nutzer_id'))

    op.drop_table('foerderer')
    with op.batch_alter_table('bewerbung', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bewerbung_status'))
        batch_op.drop_index(batch_op.f('ix_bewerbung_nutzer_id'))

    op.drop_table('bewerbung')
    op.drop_table('suchbegriff')
    op.drop_table('spende')
    op.drop_table('rechnungs_zaehler')
    with op.batch_alter_table('pressekandidat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pressekandidat_status'))

    op.drop_table('pressekandidat')
    with op.batch_alter_table('presseeintrag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presseeintrag_veroeffentlicht'))

    op.drop_table('presseeintrag')
    op.drop_table('nutzer')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_veroeffentlicht'))

    op.drop_table('news')
    with op.batch_alter_table('fehlerprotokoll', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fehlerprotokoll_zeitpunkt'))

    op.drop_table('fehlerprotokoll')
    op.drop_table('content_block')
    with op.batch_alter_table('chat_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_log_erstellt_am'))

    op.drop_table('chat_log')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
