"""nutzer newsletter einwilligung

Nachweis der Einwilligung in Rund-Mails. Bewusst KEIN Backfill: Bestandsnutzer
behandelt `flask einwilligung-anfragen` (erst Probelauf, dann --ausfuehren).

Revision ID: da901ffb142f
Revises: 6d9e1a4b3f57
Create Date: 2026-09-28 10:57:04.842862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da901ffb142f'
down_revision = '6d9e1a4b3f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutzer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('newsletter_einwilligung_am', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('einwilligung_angefragt_am', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutzer', schema=None) as batch_op:
        batch_op.drop_column('einwilligung_angefragt_am')
        batch_op.drop_column('newsletter_einwilligung_am')

    # ### end Alembic commands ###
