"""news reihenfolge

Revision ID: fa5a744c1177
Revises: 26d8c69e1502
Create Date: 2026-09-18 14:18:27.475769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5a744c1177'
down_revision = '26d8c69e1502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reihenfolge', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_news_reihenfolge'), ['reihenfolge'], unique=False)

    # ### end Alembic commands ###

    # Backfill: reihenfolge aus der bisherigen Sortierung (veroeffentlicht DESC)
    # ableiten, damit sich die Anzeige-Reihenfolge durch dieses Deploy NICHT
    # aendert -- aeltester Artikel bekommt 1, neuester die hoechste Zahl (neue
    # Artikel setzen danach max(reihenfolge)+1, landen also weiterhin oben).
    # Portabel fuer SQLite + Postgres (korrelierte Subquery statt Fensterfunktion).
    op.execute("""
        UPDATE news
        SET reihenfolge = (
            SELECT COUNT(*) FROM news AS n2
            WHERE n2.veroeffentlicht <= news.veroeffentlicht
        )
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_reihenfolge'))
        batch_op.drop_column('reihenfolge')

    # ### end Alembic commands ###
