<?php
/**
 * chat.php — OpenMycoNet RAG-Chatbot Proxy
 * Auf All-Inkl hochladen, config.php im selben Verzeichnis anlegen.
 * Endpunkt: POST /chat.php
 */

header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: https://openmyconet.de');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(204);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['error' => 'Method not allowed']);
    exit;
}

// --- Konfiguration ---
require_once __DIR__ . '/config.php'; // definiert ANTHROPIC_API_KEY

// --- Rate Limiting (max. 20 Requests / IP / Stunde, dateibasiert) ---
$rateDir  = sys_get_temp_dir() . '/omn_rl/';
if (!is_dir($rateDir)) @mkdir($rateDir, 0700, true);
$ip       = preg_replace('/[^a-f0-9:.]/i', '', $_SERVER['REMOTE_ADDR'] ?? '0');
$rateFile = $rateDir . md5($ip) . '.json';
$window   = 3600; // Sekunden
$limit    = 20;
$now      = time();
$log      = [];
if (file_exists($rateFile)) {
    $log = json_decode(file_get_contents($rateFile), true) ?: [];
}
$log = array_filter($log, fn($t) => $t > $now - $window);
if (count($log) >= $limit) {
    http_response_code(429);
    echo json_encode(['error' => 'Zu viele Anfragen — bitte später erneut versuchen.']);
    exit;
}
$log[] = $now;
file_put_contents($rateFile, json_encode(array_values($log)));

// --- Request lesen ---
$body = json_decode(file_get_contents('php://input'), true);
$message = trim($body['message'] ?? '');
$history = $body['history'] ?? [];

if (!$message) {
    http_response_code(400);
    echo json_encode(['error' => 'Kein Text übermittelt']);
    exit;
}

// --- Nachrichtenlänge begrenzen ---
if (mb_strlen($message) > 1000) {
    http_response_code(400);
    echo json_encode(['error' => 'Nachricht zu lang (max. 1000 Zeichen).']);
    exit;
}

// ---------------------------------------------------------------------------
// Wissensbasis
// ---------------------------------------------------------------------------
$chunks = [
  ['id'=>1,'lang'=>'de','title'=>'Vision & Warum','text'=>'Unter unseren Füßen liegt das älteste und weitreichendste Kommunikationsnetzwerk der Erde. Mykorrhiza-Pilze verbinden seit 400 Millionen Jahren nahezu alle Landpflanzen miteinander — sie transportieren Nährstoffe, übermitteln Warnsignale und koordinieren das Leben im Boden auf eine Weise die wir gerade erst zu verstehen beginnen. Sie senden elektrische Signale. Messbar. Reproduzierbar. Und bisher kaum entschlüsselt. OpenMycoNet stellt die einfache aber weitreichende Frage: Was passiert wenn wir aufhören, Böden nur von außen zu analysieren — und stattdessen anfangen zuzuhören was das Netzwerk selbst sendet? Das Netzwerk sendet. Wir haben gerade erst angefangen zuzuhören. Jeder BioComm-Knoten der weltweit in Betrieb geht bringt uns einen Schritt näher an das Verständnis — für alle.'],
  ['id'=>2,'lang'=>'de','title'=>'Über das Projekt','text'=>'OpenMycoNet wurde von Robert Jank, unabhängigem Erfinder aus Maintal bei Frankfurt, initiiert — ohne Institutszugehörigkeit, mit dem Ziel zu verstehen was Mykorrhiza-Netzwerke elektrisch signalisieren. Das zugrundeliegende System BioComm ist durch ein Gebrauchsmuster beim DPMA geschützt. Die Software wird als portable .exe bereitgestellt. Die Messdaten gehören der Gemeinschaft. Prinzip: Proprietary Intelligence, Open Data — das KI-Modell ist geschützt, die Daten die es trainieren sind frei.'],
  ['id'=>3,'lang'=>'de','title'=>'Mitmachen & Knoten betreiben','text'=>'Hardware leihen: BioComm-Messgerät als Leihgerät erhalten — Pfand ca. 100 € (finale Kosten folgen). Rückgabe jederzeit möglich. BioComm herunterladen: Die BioComm-Software kostenlos herunterladen — keine Installation, kein Python nötig. Elektroden setzen: Nadeln in Boden, Blumentopf oder Kompost mit Pilz- oder Mykorrhiza-Substrat. Messen & teilen: BioComm verbindet automatisch und lädt die Daten hoch. Analyse und Anonymisierung erfolgen lokal auf deinem Gerät — keine Rohdaten verlassen deinen PC.'],
  ['id'=>4,'lang'=>'de','title'=>'Datenschutz & Transparenz','text'=>'GPS-Koordinaten werden auf 10×10 km vergröbert — kein exakter Standort. Keine personenbezogenen Daten. Alle Rohdaten öffentlich zugänglich unter Creative Commons CC BY 4.0.'],
  ['id'=>5,'lang'=>'de','title'=>'Unterstützung & Spenden','text'=>'OpenMycoNet ist ein unabhängiges Citizen-Science-Projekt ohne institutionelle Förderung. Serverkosten und Weiterentwicklung werden durch freiwillige Spenden finanziert. Jeder Betrag hilft. Wir für OpenMycoNet — OpenMycoNet für alle.'],
  ['id'=>6,'lang'=>'de','title'=>'Anwendungsfelder','text'=>'Präzisionslandwirtschaft: Wenn wir die Signalmuster von Trockenstress, Nährstoffmangel und Schädlingsbefall kennen, können Landwirte reagieren bevor Schäden entstehen — ohne Chemie, ohne Flächenpauschalen. Waldschutz: Veränderungen in den Signalmustern könnten Trockenheit, Borkenkäferbefall oder Brandgefahr anzeigen — Wochen bevor es sichtbar wird. Bodenregeneration: Durch gezielte Frequenzstimulation lässt sich die Aktivität von Mykorrhiza-Netzwerken beeinflussen. Klimaschutz: Gesunde Mykorrhiza-Netzwerke binden nachweislich CO₂. Grundlagenforschung: Adamatzky et al. haben gezeigt dass Pilz-Spike-Trains strukturelle Ähnlichkeiten mit menschlichen Sprachen aufweisen.'],
  ['id'=>7,'lang'=>'de','title'=>'Fakten & Zahlen','text'=>'400 Millionen Jahre: so lange existieren Mykorrhiza-Netzwerke auf der Erde. 90% aller Landpflanzen sind mit Mykorrhiza-Pilzen verbunden. 8 Messkanäle erfasst BioComm gleichzeitig, bis zu 10.000 Hz. Ca. 100 € Pfandgebühr für ein BioComm-Leihgerät (finale Kosten folgen).'],
  ['id'=>8,'lang'=>'de','title'=>'Hardware-Verfügbarkeit & Zeitplan','text'=>'Die ersten BioComm-Prototypen befinden sich aktuell in der PCB-Fertigungsphase. Nach der Platinen-Produktion folgen Aufbau und Validierung der ersten Knoten in 3D-gedruckten IP65-Gehäusen. Ein konkretes Datum für die erste Verfügbarkeit kann noch nicht genannt werden. Das Leihgerät-Modell ist geplant mit einem Pfand von ca. 100 € — finale Kosten folgen. Interessenten können sich bereits jetzt auf der Website registrieren, um frühzeitig benachrichtigt zu werden.'],
  ['id'=>9,'lang'=>'en','title'=>'Vision & Why','text'=>'Beneath our feet lies the oldest and most extensive communication network on Earth. Mycorrhizal fungi have connected almost all land plants for 400 million years — transporting nutrients, transmitting warning signals, and coordinating life in the soil in ways we are only beginning to understand. They send electrical signals. Measurable. Reproducible. And barely deciphered so far. OpenMycoNet asks: what happens when we stop analysing soil only from the outside and start listening to what the network itself is sending? The network is transmitting. We have only just begun to listen.'],
  ['id'=>10,'lang'=>'en','title'=>'About the Project','text'=>'OpenMycoNet was initiated by Robert Jank, independent inventor from Maintal near Frankfurt — without institutional affiliation, with the goal of understanding what mycorrhizal networks signal electrically. The underlying BioComm system is protected by a utility model registered with the DPMA. The software is provided as a portable .exe. The measurement data belongs to the community. Principle: Proprietary Intelligence, Open Data — the AI model is protected, the data that trains it is free.'],
  ['id'=>11,'lang'=>'en','title'=>'Join & operate a node','text'=>'Borrow hardware: Receive a BioComm measuring device on loan — deposit approx. €100 (final costs to follow). Return at any time. Download BioComm software for free — no installation, no Python required. Place electrodes into soil, plant pot or compost with fungal or mycorrhizal substrate. BioComm connects automatically and uploads the data. Analysis and anonymisation are performed locally on your device — no raw data ever leaves your PC.'],
  ['id'=>12,'lang'=>'en','title'=>'Privacy & Transparency','text'=>'GPS coordinates are coarsened to 10×10 km — no exact location. No personal data. All raw data publicly accessible under Creative Commons CC BY 4.0.'],
  ['id'=>13,'lang'=>'en','title'=>'Support & Donations','text'=>'OpenMycoNet is an independent citizen science project without institutional funding. Server costs and further development are financed by voluntary donations. Every contribution helps. We support OpenMycoNet — OpenMycoNet supports everyone.'],
  ['id'=>14,'lang'=>'en','title'=>'Applications','text'=>'Precision agriculture: farmers can respond before damage occurs — without chemicals, without blanket treatments. Forest protection: changes in signal patterns could indicate drought, bark beetle infestation or fire risk — weeks before it becomes visible. Soil regeneration: targeted frequency stimulation can influence mycorrhizal network activity. Climate protection: healthy mycorrhizal networks demonstrably sequester CO₂. Fundamental research: Adamatzky et al. have shown that fungal spike trains have structural similarities to human languages.'],
  ['id'=>15,'lang'=>'en','title'=>'Facts & Numbers','text'=>'400 million years: mycorrhizal networks have existed on Earth. 90% of all land plants are connected to mycorrhizal fungi. 8 channels recorded simultaneously by BioComm, up to 10,000 Hz. Approx. €100 deposit for a BioComm loan device (final costs to follow).'],
  ['id'=>16,'lang'=>'en','title'=>'Hardware availability & timeline','text'=>'The first BioComm prototypes are currently in the PCB manufacturing phase. After board production, assembly and validation of the first nodes in 3D-printed IP65 enclosures will follow. A specific availability date cannot be given yet. The loan device model is planned with a deposit of approx. €100 — final costs to follow. Interested parties can already register on the website to be notified early.'],
  ['id'=>17,'lang'=>'nl','title'=>'Visie & Waarom','text'=>'Onder onze voeten ligt het oudste communicatienetwerk van de aarde. Mycorrhizaschimmels verbinden al 400 miljoen jaar vrijwel alle landplanten. Ze zenden elektrische signalen. Meetbaar. Reproduceerbaar. OpenMycoNet vraagt: wat gebeurt er als we ophouden bodems alleen van buitenaf te analyseren? Het netwerk zendt. We zijn er nog maar net mee begonnen te luisteren.'],
  ['id'=>18,'lang'=>'nl','title'=>'Over het project','text'=>'OpenMycoNet werd geïnitieerd door Robert Jank, onafhankelijk uitvinder uit Maintal bij Frankfurt. Het BioComm-systeem is beschermd door een gebruiksmodel bij het DPMA. De software wordt aangeboden als draagbare .exe. De meetgegevens zijn eigendom van de gemeenschap. Principe: Proprietary Intelligence, Open Data.'],
  ['id'=>19,'lang'=>'nl','title'=>'Meedoen & knooppunt beheren','text'=>'Hardware lenen: BioComm-meetapparaat als leentoestel — borg ca. €100 (definitieve kosten volgen). BioComm downloaden: gratis, geen installatie nodig. Elektroden plaatsen in bodem of bloempot met schimmelsubstraat. BioComm maakt automatisch verbinding — geen ruwe data verlaat je pc.'],
  ['id'=>20,'lang'=>'nl','title'=>'Privacy & Transparantie','text'=>'GPS-coördinaten worden vergroot naar 10×10 km — geen exacte locatie. Geen persoonsgegevens. Alle ruwe data openbaar toegankelijk onder Creative Commons CC BY 4.0.'],
  ['id'=>21,'lang'=>'nl','title'=>'Ondersteuning & Donaties','text'=>'OpenMycoNet is een onafhankelijk citizen science-project zonder institutionele financiering. Serverkosten worden gefinancierd door vrijwillige donaties. Elk bedrag helpt.'],
  ['id'=>22,'lang'=>'nl','title'=>'Toepassingen','text'=>'Precisielandbouw: reageren voordat schade ontstaat. Bosbescherming: signaalveranderingen kunnen droogte of plaagaantasting signaleren weken voordat het zichtbaar wordt. Bodemregeneratie via frequentiestimulatie. Klimaatbescherming: mycorrhizanetwerken binden CO₂.'],
  ['id'=>23,'lang'=>'nl','title'=>'Feiten & Cijfers','text'=>'400 miljoen jaar oud. 90% van alle landplanten verbonden met mycorrhizaschimmels. 8 kanalen tegelijk, tot 10.000 Hz. Borg ca. €100 (definitief te bevestigen).'],
  ['id'=>24,'lang'=>'nl','title'=>'Hardware-beschikbaarheid & tijdlijn','text'=>'De eerste BioComm-prototypes bevinden zich in de PCB-fabricagefase. Na de productie van de printplaten volgen assemblage en validatie van de eerste knooppunten in 3D-geprinte IP65-behuizingen. Een concrete beschikbaarheidsdatum kan nog niet worden gegeven. Geïnteresseerden kunnen zich nu al registreren om tijdig geïnformeerd te worden.'],
  ['id'=>25,'lang'=>'fr','title'=>'Vision & Pourquoi','text'=>'Sous nos pieds se trouve le réseau de communication le plus ancien de la Terre. Les champignons mycorhiziens relient presque toutes les plantes terrestres depuis 400 millions d\'années. Ils émettent des signaux électriques. Mesurables. Reproductibles. Le réseau émet. Nous venons tout juste de commencer à écouter.'],
  ['id'=>26,'lang'=>'fr','title'=>'À propos du projet','text'=>'OpenMycoNet a été initié par Robert Jank, inventeur indépendant de Maintal près de Francfort. Le système BioComm est protégé par un modèle d\'utilité déposé auprès du DPMA. Principe: Proprietary Intelligence, Open Data — le modèle d\'IA est protégé, les données qui l\'entraînent sont libres.'],
  ['id'=>27,'lang'=>'fr','title'=>'Participer & exploiter un nœud','text'=>'Emprunter le matériel BioComm en prêt — caution env. 100 €. Télécharger BioComm gratuitement, sans installation. Placer les électrodes dans le sol ou le pot. BioComm se connecte automatiquement — aucune donnée brute ne quitte votre PC.'],
  ['id'=>28,'lang'=>'fr','title'=>'Confidentialité & Transparence','text'=>'Les coordonnées GPS sont arrondies à 10×10 km — aucune localisation précise. Aucune donnée personnelle. Toutes les données brutes accessibles publiquement sous CC BY 4.0.'],
  ['id'=>29,'lang'=>'fr','title'=>'Soutien & Dons','text'=>'OpenMycoNet est un projet de science citoyenne indépendant sans financement institutionnel. Les coûts de serveur sont financés par des dons volontaires. Chaque contribution compte.'],
  ['id'=>30,'lang'=>'fr','title'=>'Applications','text'=>'Agriculture de précision: réagir avant les dégâts, sans produits chimiques. Protection des forêts: des changements de signaux peuvent indiquer sécheresse ou infestation des semaines à l\'avance. Régénération des sols par stimulation fréquentielle. Protection du climat: les réseaux mycorhiziens séquestrent du CO₂.'],
  ['id'=>31,'lang'=>'fr','title'=>'Faits & Chiffres','text'=>'400 millions d\'années d\'existence. 90% des plantes terrestres connectées. 8 canaux simultanés jusqu\'à 10 000 Hz. Caution env. 100 € (coût final à confirmer).'],
  ['id'=>32,'lang'=>'fr','title'=>'Disponibilité matérielle & calendrier','text'=>'Les premiers prototypes BioComm sont en phase de fabrication de circuits imprimés. Après la production des cartes, l\'assemblage et la validation des premiers nœuds dans des boîtiers IP65 imprimés en 3D suivront. Une date de disponibilité précise ne peut pas encore être donnée. Les personnes intéressées peuvent déjà s\'inscrire sur le site web pour être informées rapidement.'],
  ['id'=>33,'lang'=>'es','title'=>'Visión & Por qué','text'=>'Bajo nuestros pies se encuentra la red de comunicación más antigua de la Tierra. Los hongos micorrícicos llevan 400 millones de años conectando las plantas terrestres. Emiten señales eléctricas. Medibles. Reproducibles. La red transmite. Apenas hemos empezado a escuchar.'],
  ['id'=>34,'lang'=>'es','title'=>'Sobre el proyecto','text'=>'OpenMycoNet fue iniciado por Robert Jank, inventor independiente de Maintal. El sistema BioComm está protegido por un modelo de utilidad registrado en la DPMA. Principio: Proprietary Intelligence, Open Data — el modelo de IA está protegido, los datos que lo entrenan son libres.'],
  ['id'=>35,'lang'=>'es','title'=>'Participar & operar un nodo','text'=>'Tomar hardware BioComm en préstamo — depósito aprox. 100 €. Descargar BioComm gratis, sin instalación. Colocar electrodos en tierra o maceta con sustrato micorrícico. BioComm se conecta automáticamente — ningún dato bruto abandona tu PC.'],
  ['id'=>36,'lang'=>'es','title'=>'Privacidad & Transparencia','text'=>'Las coordenadas GPS se redondean a 10×10 km — sin ubicación exacta. Sin datos personales. Todos los datos brutos accesibles públicamente bajo CC BY 4.0.'],
  ['id'=>37,'lang'=>'es','title'=>'Apoyo & Donaciones','text'=>'OpenMycoNet es un proyecto de ciencia ciudadana independiente sin financiación institucional. Los costes de servidor se financian con donaciones voluntarias. Cada aportación cuenta.'],
  ['id'=>38,'lang'=>'es','title'=>'Aplicaciones','text'=>'Agricultura de precisión: reaccionar antes de los daños, sin químicos. Protección forestal: cambios en señales pueden indicar sequía o infestación semanas antes. Regeneración del suelo por estimulación frecuencial. Protección del clima: las redes micorrícicas secuestran CO₂.'],
  ['id'=>39,'lang'=>'es','title'=>'Hechos & Cifras','text'=>'400 millones de años de existencia. 90% de las plantas terrestres conectadas. 8 canales simultáneos hasta 10.000 Hz. Depósito aprox. €100 (costes definitivos por confirmar).'],
  ['id'=>40,'lang'=>'es','title'=>'Disponibilidad de hardware & calendario','text'=>'Los primeros prototipos BioComm están en fase de fabricación de PCB. Tras la producción de las placas, seguirán el ensamblaje y la validación de los primeros nodos en carcasas IP65 impresas en 3D. Aún no se puede dar una fecha concreta de disponibilidad. Los interesados ya pueden registrarse en el sitio web para ser notificados con anticipación.'],
  ['id'=>41,'lang'=>'de','title'=>'Vorwort — Was ist OpenMycoNet?','text'=>'OpenMycoNet ist ein Citizen-Science-Projekt. Wir messen die bioelektrischen Signale von Pilznetzwerken im Boden — an so vielen Orten wie möglich, über so lange Zeit wie möglich. Was wir dabei lernen, teilen wir offen. Wir sind kein Forschungsinstitut, haben keine Professoren unter uns. Was wir haben, ist Neugier, ein bisschen Messtechnik und die Überzeugung, dass Bürgerinnen und Bürger einen echten Beitrag zur Wissenschaft leisten können — wenn man ihnen die richtigen Werkzeuge gibt.'],
  ['id'=>42,'lang'=>'de','title'=>'Das unsichtbare Netzwerk unter unseren Füßen','text'=>'Direkt unter unserer Sohle, in jedem Schritt durch einen Wald, erstreckt sich ein Netzwerk von unvorstellbarer Dichte. Fäden, feiner als ein menschliches Haar — Milliarden davon in jedem Kubikzentimeter Erde. Dieses Netzwerk lebt, wächst, reagiert, transportiert, kommuniziert. Und es hält den Wald am Leben — schon seit Hunderten von Millionen Jahren.'],
  ['id'=>43,'lang'=>'de','title'=>'Was ist eigentlich ein Pilz?','text'=>'Was wir als Pilz wahrnehmen — Hut, Stiel, das Gebilde das wir pflücken — ist nicht der Organismus selbst. Es ist sein Fortpflanzungsorgan, seine Frucht. Der eigentliche Pilz lebt im Verborgenen, unter der Erde, und ist meist um ein Vielfaches größer als das was wir je zu Gesicht bekommen. Pilze bilden ein eigenes Reich — die Fungi. Sie haben kein Chlorophyll und können keine Photosynthese betreiben. Stattdessen verdauen sie außerhalb ihres Körpers: Sie scheiden Enzyme aus, die organisches Material aufschließen, und nehmen Nährstoffe durch ihre Zellwände auf. Das macht sie zu den großen Zerlegern der Natur — ohne die kein Wald funktionieren würde.'],
  ['id'=>44,'lang'=>'de','title'=>'Das Mycel — der eigentliche Organismus','text'=>'Der eigentliche Körper eines Pilzes heißt Mycel. Es besteht aus haarfeinen Fäden — den Hyphen — die sich durch Erde, Holz und Laub weben. In einer einzigen Handvoll Waldboden können sich mehr Pilzfäden befinden als Straßen in einer deutschen Kleinstadt. Der Biologe David Read hat errechnet, dass die Gesamtlänge aller Pilzhyphen in den obersten Bodenschichten die Entfernung von der Erde zur Sonne um ein Vielfaches übertrifft. Das ist keine Metapher — das ist Biologie. Mycel hat kein Gehirn, kein Nervensystem — und trotzdem verhält es sich auf eine Art, die wir bei einem Tier als intelligent bezeichnen würden. Pilzmycel findet den kürzesten Weg zwischen Nahrungsquellen und optimiert sein Netzwerk ständig.'],
  ['id'=>45,'lang'=>'de','title'=>'Mykorrhiza — die älteste Partnerschaft der Welt','text'=>'Vor etwa 450 Millionen Jahren wagten sich die ersten Pflanzen aus dem Wasser ans Land — wahrscheinlich weil sie Pilze als Partner mitbrachten. Diese Verbindung nennen wir heute Mykorrhiza (griechisch: mykes = Pilz, rhiza = Wurzel). Das Prinzip: Die Pflanze liefert dem Pilz Zucker — bis zu 30 Prozent ihrer Glukose-Produktion. Der Pilz liefert der Pflanze Wasser und Nährstoffe tief im Boden, besonders Phosphor, den Pflanzen dringend brauchen aber schwer erreichen können. Pflanzen mit funktionierender Mykorrhiza wachsen besser, überstehen Trockenheit leichter, sind widerstandsfähiger gegen Krankheiten und brauchen weniger Dünger. Über 90 Prozent aller Landpflanzen gehen Mykorrhiza-Partnerschaften ein.'],
  ['id'=>46,'lang'=>'de','title'=>'Das Waldnetz — Verbindungen zwischen Bäumen','text'=>'Mykorrhizanetzwerke verbinden Wurzeln verschiedener Pflanzen miteinander. Die Waldökologin Suzanne Simard hat nachgewiesen, dass Kohlenstoff — also Zucker — tatsächlich von großen Bäumen zu kleineren, jüngeren Pflanzen wandert: nicht durch die Luft, sondern durch das Pilznetzwerk im Boden. Neben Kohlenstoff fließen auch Stickstoff, Phosphor und Wasser durch das Netz. Es gibt Studien, die zeigen dass bei Schädlingsbefall chemische Signale über das Netzwerk zu Nachbarpflanzen gelangen können. Der Transport selbst ist real und mehrfach repliziert.'],
  ['id'=>47,'lang'=>'de','title'=>'Elektrische Signale in Pilznetzwerken','text'=>'Pilzmycel leitet elektrische Signale. Seit den frühen 1990er Jahren untersucht Andrew Adamatzky von der University of the West of England die elektrophysiologischen Eigenschaften von Pilzen. Die Signale folgen Mustern — regelmäßige Impulse, die auf äußere Reize reagieren. Adamatzky hat Hinweise gefunden, dass Pilze bis zu 50 verschiedene Signalmuster produzieren können. Ob das eine Form von Informationsverarbeitung ist, ist eine der spannendsten offenen Fragen der modernen Biologie. Es ist genau diese Frage, die OpenMycoNet beschäftigt: Wenn Pilznetzwerke elektrische Signale tragen — dann müsste man sie messen können. Systematisch, an vielen Orten, über lange Zeit.'],
  ['id'=>48,'lang'=>'de','title'=>'Was Mykorrhizanetzwerke bedroht','text'=>'Tiefes Pflügen — das Standardverfahren der konventionellen Landwirtschaft — zerschneidet Mykorrhizanetzwerke physisch. Fungizide schädigen Mykorrhizapilze. Synthetische Phosphordünger machen Mykorrhiza aus Sicht der Pflanze überflüssig: Stark gedüngte Böden verlieren ihre Mykorrhiza-Aktivität und werden abhängiger vom Kunstdünger. Schwere Maschinen verdichten den Boden und verschlechtern die Lebensbedingungen für Pilzmycel. Bodenversiegelung durch Beton und Asphalt unterbricht das Bodennetzwerk dauerhaft. Das Problem: Die Wunde bleibt unsichtbar — es gibt bisher kein Instrument, das den Zustand eines Mykorrhizanetzwerks vor und nach einem Eingriff dokumentiert.'],
  ['id'=>49,'lang'=>'de','title'=>'Was die Wissenschaft weiß — und was noch offen ist','text'=>'Was wir ziemlich sicher wissen: Mykorrhizanetzwerke sind in über 90 Prozent aller Landpflanzen präsent. Unter Stressbedingungen zeigen Studien Ertragssteigerungen von 20–30 Prozent. Der Transport von Nährstoffen und Kohlenstoff über Pilznetzwerke ist mehrfach unabhängig repliziert. Pilzmycel leitet elektrische Signale. Was noch offen ist: Wie viel CO₂ Mykorrhizanetzwerke tatsächlich binden, ist überraschend unklar — neuere Studien zeigen widersprüchliche Ergebnisse. Was fast vollständig fehlt: die Gesamtbilanz. Die meisten Studien messen einen Parameter und halten alles andere konstant. CO₂-Bilanz, Ertrag, Wasserverbrauch und Bodengesundheit gleichzeitig am selben Standort — das hat noch niemand systematisch gemessen.'],
  ['id'=>50,'lang'=>'de','title'=>'Die BioComm-Technologie','text'=>'OpenMycoNet entwickelt preisgünstige Messknoten — BioComm-Nodes — die bioelektrische Signale im Boden aufzeichnen. Jeder Knoten enthält einen Mikrocontroller, mehrere Messelektroden und eine Speichereinheit. Er wird im Boden platziert, sammelt kontinuierlich Daten und überträgt sie periodisch an einen zentralen Server. Dort werden Muster erkannt, Standorte verglichen, Veränderungen über Zeit dokumentiert. Das Ziel: zu lernen, wie sich ein gesundes Netzwerk von einem gestressten unterscheidet — und was mit dem Netzwerk passiert, wenn in einen Standort eingegriffen wird. Alle Daten sind offen zugänglich.'],
  ['id'=>51,'lang'=>'de','title'=>'Warum Citizen Science — und warum jetzt?','text'=>'Professionelle Forschende können einen Standort messen, vielleicht zehn. Was wir brauchen, sind hundert Standorte — tausend, über Jahre hinweg. Das schafft keine Universität alleine. Die Technologie ist heute erschwinglich: Ein vollständiger Messknoten kostet weniger als ein gutes Abendessen. Was wir brauchen, sind Menschen mit Gärten, Feldern, Waldgrundstücken — die bereit sind, ein kleines Gerät in den Boden zu stecken und uns zu helfen, das Unsichtbare sichtbar zu machen.'],
  ['id'=>52,'lang'=>'de','title'=>'Die langfristige Vision von OpenMycoNet','text'=>'OpenMycoNet träumt von einem Netzwerk, das dauerhaft dokumentiert was unter unseren Füßen passiert. Das belegen kann, wann ein Eingriff ein Netzwerk schädigt. Das helfen kann, Mykorrhizanetzwerke irgendwann als das rechtlich anzuerkennen, was sie biologisch sind: lebende, schützenswerte Organismen. Jede Messung bringt uns einem Schritt näher. Das Netz ist da. Wir lernen gerade erst, es zu hören.'],
  ['id'=>53,'lang'=>'en','title'=>'Introduction — What is OpenMycoNet?','text'=>'OpenMycoNet is a citizen science project. We measure the bioelectrical signals of fungal networks in the soil — at as many locations as possible, for as long as possible. What we learn, we share openly. We are not a research institute and have no professors among us. What we have is curiosity, a bit of measurement technology, and the conviction that citizens can make a genuine contribution to science — if given the right tools.'],
  ['id'=>54,'lang'=>'en','title'=>'The invisible network beneath our feet','text'=>'Directly beneath our feet, in every step through a forest, lies a network of unimaginable density. Threads finer than a human hair — billions of them in every cubic centimetre of soil. This network lives, grows, reacts, transports, communicates. And it has kept forests alive for hundreds of millions of years.'],
  ['id'=>55,'lang'=>'en','title'=>'What exactly is a fungus?','text'=>'What we perceive as a mushroom — the cap, the stem, the structure we pick or photograph — is not the organism itself. It is its reproductive organ, its fruit. The actual fungus lives hidden, underground, and is usually many times larger than what we ever see. Fungi form their own kingdom — the Fungi. They have no chlorophyll and cannot photosynthesise. Instead they digest outside their body: secreting enzymes that break down organic material, then absorbing nutrients through their cell walls. This makes them nature\'s great decomposers — without whom no forest would function.'],
  ['id'=>56,'lang'=>'en','title'=>'Mycelium — the actual organism','text'=>'The actual body of a fungus is called mycelium. It consists of hair-fine threads — hyphae — that weave through soil, wood and leaf litter. A single handful of forest soil can contain more fungal threads than there are roads in a small German town. Biologist David Read calculated that the total length of all fungal hyphae in the upper soil layers exceeds the distance from Earth to the Sun many times over. That is not a metaphor — it is biology. Mycelium has no brain, no nervous system — and yet it behaves in ways we would call intelligent in an animal. Fungal mycelium finds the shortest path between food sources and constantly optimises its network.'],
  ['id'=>57,'lang'=>'en','title'=>'Mycorrhiza — the oldest partnership on Earth','text'=>'About 450 million years ago, the first plants ventured from water onto land — probably because they brought fungi as partners. We call this connection mycorrhiza (Greek: mykes = fungus, rhiza = root). The principle: the plant supplies the fungus with sugar — up to 30 percent of its glucose production. The fungus supplies the plant with water and nutrients deep in the soil, especially phosphorus, which plants urgently need but struggle to reach. Plants with functioning mycorrhiza grow better, survive drought more easily, are more resistant to disease and need less fertiliser. Over 90 percent of all land plants form mycorrhizal partnerships.'],
  ['id'=>58,'lang'=>'en','title'=>'The forest web — connections between trees','text'=>'Mycorrhizal networks connect the roots of different plants. Forest ecologist Suzanne Simard demonstrated that carbon — sugar — actually travels from large trees to smaller, younger plants: not through the air, but through the fungal network in the soil. Besides carbon, nitrogen, phosphorus and water also flow through the network. Studies indicate that when pests attack, chemical signals can travel via the network to neighbouring plants, which then produce their own defence substances. The transport itself is real and has been independently replicated multiple times.'],
  ['id'=>59,'lang'=>'en','title'=>'Electrical signals in fungal networks','text'=>'Fungal mycelium conducts electrical signals. Since the early 1990s, Andrew Adamatzky at the University of the West of England has been studying the electrophysiological properties of fungi. The signals follow patterns — regular impulses that respond to external stimuli. Adamatzky has found evidence that fungi can produce up to 50 different signal patterns. Whether this constitutes a form of information processing is one of the most exciting open questions in modern biology. This is exactly the question that drives OpenMycoNet: if fungal networks carry electrical signals, they should be measurable — systematically, at many locations, over long periods.'],
  ['id'=>60,'lang'=>'en','title'=>'What threatens mycorrhizal networks','text'=>'Deep ploughing — the standard method in conventional agriculture — physically cuts through mycorrhizal networks. Fungicides damage mycorrhizal fungi. Synthetic phosphorus fertilisers make mycorrhiza unnecessary from the plant\'s perspective: heavily fertilised soils lose their mycorrhizal activity and become more dependent on artificial fertiliser. Heavy machinery compacts soil and worsens living conditions for fungal mycelium. Sealing the soil with concrete and asphalt permanently disrupts the soil network. The problem: the damage remains invisible — there is currently no instrument that documents the state of a mycorrhizal network before and after an intervention.'],
  ['id'=>61,'lang'=>'en','title'=>'What science knows — and what remains open','text'=>'What we know fairly certainly: mycorrhizal networks are present in over 90 percent of all land plants. Under stress conditions, studies show yield increases of 20–30 percent. The transport of nutrients and carbon through fungal networks has been independently replicated multiple times. Fungal mycelium conducts electrical signals. What remains open: how much CO₂ mycorrhizal networks actually bind is surprisingly unclear — newer studies show contradictory results. What is almost entirely missing: the complete picture. Most studies measure one parameter and hold everything else constant. CO₂ balance, yield, water consumption and soil health simultaneously at the same site — that has not yet been systematically measured.'],
  ['id'=>62,'lang'=>'en','title'=>'The BioComm technology','text'=>'OpenMycoNet develops affordable measurement nodes — BioComm Nodes — that record bioelectrical signals in the soil. Each node contains a microcontroller, several measurement electrodes and a storage unit. It is placed in the soil, continuously collects data and periodically transmits it to a central server. There, patterns are recognised, locations compared, changes documented over time. The goal: to learn how a healthy network differs from a stressed one — and what happens to the network when a site is disturbed. All data is openly accessible.'],
  ['id'=>63,'lang'=>'en','title'=>'Why citizen science — and why now?','text'=>'Professional researchers can measure one site, perhaps ten. What we need are a hundred sites — a thousand, over years. No university can do that alone. The technology is affordable today: a complete measurement node costs less than a good dinner out. What we need are people with gardens, fields, woodland plots — willing to put a small device in the ground and help us make the invisible visible.'],
  ['id'=>64,'lang'=>'en','title'=>'The long-term vision of OpenMycoNet','text'=>'OpenMycoNet envisions a network that permanently documents what happens beneath our feet. That can prove when an intervention damages a network. That can help mycorrhizal networks eventually be recognised legally for what they are biologically: living, protected organisms. Every measurement brings us one step closer. The network is there. We are only just learning to listen to it.'],
  ['id'=>65,'lang'=>'nl','title'=>'Inleiding — Wat is OpenMycoNet?','text'=>'OpenMycoNet is een citizen science-project. We meten de bio-elektrische signalen van schimmelnetwerken in de bodem — op zoveel mogelijk locaties, zo lang mogelijk. Wat we leren, delen we openlijk. We zijn geen onderzoeksinstituut. Wat we hebben is nieuwsgierigheid, wat meettechnologie en de overtuiging dat burgers een echte bijdrage kunnen leveren aan de wetenschap — als ze de juiste tools krijgen.'],
  ['id'=>66,'lang'=>'nl','title'=>'Het onzichtbare netwerk onder onze voeten','text'=>'Vlak onder onze voeten, bij elke stap door een bos, strekt zich een netwerk van onvoorstelbare dichtheid uit. Draden fijner dan een menselijk haar — miljarden ervan in elke kubieke centimeter grond. Dit netwerk leeft, groeit, reageert, transporteert, communiceert. En het houdt het bos al honderden miljoenen jaren in leven.'],
  ['id'=>67,'lang'=>'nl','title'=>'Wat is eigenlijk een paddenstoel?','text'=>'Wat wij als paddenstoel waarnemen — hoed, steel, het ding dat we plukken — is niet het organisme zelf. Het is zijn voortplantingsorgaan, zijn vrucht. Het eigenlijke organisme leeft verborgen, ondergronds. Schimmels vormen een eigen rijk — de Fungi. Ze hebben geen chlorofyl en kunnen niet aan fotosynthese doen. In plaats daarvan verteren ze buiten hun lichaam: ze scheiden enzymen uit die organisch materiaal afbreken en nemen voedingsstoffen op door hun celwanden. Dit maakt hen tot de grote afbrekers van de natuur — zonder wie geen enkel bos zou functioneren.'],
  ['id'=>68,'lang'=>'nl','title'=>'Het mycelium — het eigenlijke organisme','text'=>'Het eigenlijke lichaam van een schimmel heet mycelium. Het bestaat uit haarfijne draden — hyfen — die zich door aarde, hout en bladeren weven. In één handvol bosgrond kunnen meer schimmeldraden zitten dan er wegen zijn in een kleine stad. Bioloog David Read berekende dat de totale lengte van alle schimmeldraden in de bovenste bodemlagen de afstand van de aarde naar de zon vele malen overtreft. Mycelium heeft geen brein, geen zenuwstelsel — en toch gedraagt het zich op een manier die we bij een dier intelligent zouden noemen.'],
  ['id'=>69,'lang'=>'nl','title'=>'Mycorrhiza — het oudste partnerschap op aarde','text'=>'Ongeveer 450 miljoen jaar geleden waagden de eerste planten de stap van water naar land — waarschijnlijk met schimmels als partners. We noemen deze verbinding mycorrhiza (Grieks: mykes = schimmel, rhiza = wortel). Het principe: de plant levert de schimmel suiker — tot 30 procent van haar glucoseproductie. De schimmel levert de plant water en voedingsstoffen diep in de bodem, met name fosfor. Planten met werkende mycorrhiza groeien beter, doorstaan droogte makkelijker en hebben minder kunstmest nodig. Meer dan 90 procent van alle landplanten gaat mycorrhiza-partnerschappen aan.'],
  ['id'=>70,'lang'=>'nl','title'=>'Het bosnetwerk — verbindingen tussen bomen','text'=>'Mycorrhizanetwerken verbinden de wortels van verschillende planten. Bosecolog Suzanne Simard heeft aangetoond dat koolstof — suiker — daadwerkelijk van grote bomen naar kleinere, jongere planten stroomt: niet door de lucht, maar via het schimmelnetwerk in de bodem. Naast koolstof stromen ook stikstof, fosfor en water door het netwerk. Studies wijzen erop dat bij plaagaanvallen chemische signalen via het netwerk naar naburige planten kunnen worden gestuurd.'],
  ['id'=>71,'lang'=>'nl','title'=>'Elektrische signalen in schimmelnetwerken','text'=>'Schimmelmycelium geleidt elektrische signalen. Sinds de vroege jaren negentig onderzoekt Andrew Adamatzky aan de University of the West of England de elektrofysiologische eigenschappen van schimmels. De signalen volgen patronen — regelmatige impulsen die reageren op externe prikkels. Adamatzky heeft aanwijzingen gevonden dat schimmels tot 50 verschillende signaalpatronen kunnen produceren. Of dit een vorm van informatieverwerking is, is een van de meest fascinerende open vragen in de moderne biologie. Dit is precies wat OpenMycoNet drijft: als schimmelnetwerken elektrische signalen dragen, moeten ze meetbaar zijn.'],
  ['id'=>72,'lang'=>'nl','title'=>'Wat mycorrhizanetwerken bedreigt','text'=>'Diep ploegen — de standaardmethode in de conventionele landbouw — snijdt mycorrhizanetwerken fysiek door. Fungiciden beschadigen mycorrhizaschimmels. Synthetische fosfaatmeststoffen maken mycorrhiza overbodig: zwaar bemeste bodems verliezen hun mycorrhiza-activiteit. Zware machines verdichten de bodem. Asfalt en beton onderbreken het bodemnetwerk permanent. Het probleem: de schade blijft onzichtbaar — er is momenteel geen instrument dat de toestand van een mycorrhizanetwerk vóór en na een ingreep documenteert.'],
  ['id'=>73,'lang'=>'nl','title'=>'Wat de wetenschap weet — en wat nog open is','text'=>'Wat we vrij zeker weten: mycorrhizanetwerken zijn aanwezig bij meer dan 90 procent van alle landplanten. Onder stress laten studies opbrengststijgingen van 20–30 procent zien. Het transport van voedingsstoffen via schimmelnetwerken is meerdere malen onafhankelijk bevestigd. Schimmelmycelium geleidt elektrische signalen. Wat nog open is: hoeveel CO₂ mycorrhizanetwerken werkelijk binden is verrassend onduidelijk. Wat bijna volledig ontbreekt: het totaalplaatje — CO₂-balans, opbrengst, waterverbruik en bodemgezondheid tegelijk op dezelfde locatie meten.'],
  ['id'=>74,'lang'=>'nl','title'=>'De BioComm-technologie','text'=>'OpenMycoNet ontwikkelt betaalbare meetknooppunten — BioComm Nodes — die bio-elektrische signalen in de bodem registreren. Elk knooppunt bevat een microcontroller, meerdere meetelektroden en een opslageenheid. Het wordt in de bodem geplaatst, verzamelt continu data en stuurt die periodiek naar een centrale server. Daar worden patronen herkend, locaties vergeleken, veranderingen over tijd gedocumenteerd. Alle data is openbaar toegankelijk.'],
  ['id'=>75,'lang'=>'nl','title'=>'Waarom citizen science — en waarom nu?','text'=>'Professionele onderzoekers kunnen één locatie meten, misschien tien. Wat we nodig hebben zijn honderd locaties — duizend, over jaren. Geen universiteit kan dat alleen. De technologie is vandaag betaalbaar: een complete meetnode kost minder dan een goed etentje. Wat we nodig hebben zijn mensen met tuinen, akkers, bosgronden — die bereid zijn een klein apparaatje in de grond te steken.'],
  ['id'=>76,'lang'=>'nl','title'=>'De langetermijnvisie van OpenMycoNet','text'=>'OpenMycoNet droomt van een netwerk dat permanent documenteert wat er onder onze voeten gebeurt. Dat kan bewijzen wanneer een ingreep een netwerk beschadigt. Dat kan helpen mycorrhizanetwerken juridisch te erkennen als wat ze biologisch zijn: levende, beschermenswaardige organismen. Elke meting brengt ons een stap dichterbij. Het netwerk is er. We leren het nu pas te beluisteren.'],
  ['id'=>77,'lang'=>'fr','title'=>'Introduction — Qu\'est-ce qu\'OpenMycoNet ?','text'=>'OpenMycoNet est un projet de science citoyenne. Nous mesurons les signaux bioélectriques des réseaux fongiques dans le sol — dans le plus grand nombre d\'endroits possible, sur la plus longue durée possible. Ce que nous apprenons, nous le partageons librement. Nous ne sommes pas un institut de recherche. Ce que nous avons, c\'est de la curiosité, un peu de technologie de mesure et la conviction que les citoyens peuvent contribuer réellement à la science — si on leur donne les bons outils.'],
  ['id'=>78,'lang'=>'fr','title'=>'Le réseau invisible sous nos pieds','text'=>'Directement sous nos pieds, à chaque pas dans une forêt, s\'étend un réseau d\'une densité inimaginable. Des fils plus fins qu\'un cheveu humain — des milliards dans chaque centimètre cube de terre. Ce réseau vit, grandit, réagit, transporte, communique. Et il maintient la forêt en vie depuis des centaines de millions d\'années.'],
  ['id'=>79,'lang'=>'fr','title'=>'Qu\'est-ce qu\'un champignon exactement ?','text'=>'Ce que nous percevons comme un champignon — le chapeau, le pied, la structure que nous cueillons — n\'est pas l\'organisme lui-même. C\'est son organe reproducteur, son fruit. Le champignon réel vit caché, sous terre, et est généralement bien plus grand que ce que nous voyons jamais. Les champignons forment leur propre règne — les Fungi. Ils n\'ont pas de chlorophylle et ne peuvent pas faire de photosynthèse. Ils digèrent en dehors de leur corps en sécrétant des enzymes qui décomposent la matière organique. Ce sont les grands décomposeurs de la nature — sans lesquels aucune forêt ne fonctionnerait.'],
  ['id'=>80,'lang'=>'fr','title'=>'Le mycélium — l\'organisme réel','text'=>'Le corps réel d\'un champignon s\'appelle mycélium. Il est constitué de fils très fins — les hyphes — qui se tissent à travers la terre, le bois et les feuilles. Dans une seule poignée de terre forestière, il peut y avoir plus de fils fongiques que de routes dans une petite ville. Le biologiste David Read a calculé que la longueur totale de tous les hyphes fongiques dans les couches supérieures du sol dépasse de nombreuses fois la distance de la Terre au Soleil. Le mycélium n\'a ni cerveau ni système nerveux — et pourtant il se comporte d\'une façon que nous qualifierions d\'intelligente chez un animal.'],
  ['id'=>81,'lang'=>'fr','title'=>'La mycorhize — le plus vieux partenariat du monde','text'=>'Il y a environ 450 millions d\'années, les premières plantes ont osé quitter l\'eau pour s\'aventurer sur la terre ferme — probablement parce qu\'elles avaient des champignons comme partenaires. Nous appelons cette connexion mycorhize (grec : mykes = champignon, rhiza = racine). Le principe : la plante fournit au champignon du sucre — jusqu\'à 30 % de sa production de glucose. Le champignon fournit à la plante eau et nutriments profondément dans le sol, notamment du phosphore. Les plantes avec des mycorhizes fonctionnelles poussent mieux, supportent mieux la sécheresse et ont besoin de moins d\'engrais. Plus de 90 % des plantes terrestres forment des partenariats mycorhiziens.'],
  ['id'=>82,'lang'=>'fr','title'=>'Le réseau forestier — connexions entre arbres','text'=>'Les réseaux mycorhiziens connectent les racines de différentes plantes. L\'écologiste forestière Suzanne Simard a démontré que le carbone — le sucre — voyage réellement des grands arbres vers les plus petits : non pas par l\'air, mais via le réseau fongique dans le sol. En plus du carbone, l\'azote, le phosphore et l\'eau circulent également dans le réseau. Des études indiquent que lors d\'attaques de ravageurs, des signaux chimiques peuvent passer via le réseau vers les plantes voisines.'],
  ['id'=>83,'lang'=>'fr','title'=>'Signaux électriques dans les réseaux fongiques','text'=>'Le mycélium fongique conduit des signaux électriques. Depuis le début des années 1990, Andrew Adamatzky à l\'Université de l\'Ouest de l\'Angleterre étudie les propriétés électrophysiologiques des champignons. Les signaux suivent des schémas — des impulsions régulières qui répondent à des stimuli externes. Adamatzky a trouvé des preuves que les champignons peuvent produire jusqu\'à 50 schémas de signaux différents. Si cela constitue une forme de traitement de l\'information est l\'une des questions ouvertes les plus passionnantes de la biologie moderne. C\'est exactement ce qui motive OpenMycoNet.'],
  ['id'=>84,'lang'=>'fr','title'=>'Ce qui menace les réseaux mycorhiziens','text'=>'Le labour profond — méthode standard de l\'agriculture conventionnelle — coupe physiquement les réseaux mycorhiziens. Les fongicides endommagent les champignons mycorhiziens. Les engrais phosphorés synthétiques rendent la mycorhize superflue : les sols très fertilisés perdent leur activité mycorhizienne. Les machines lourdes compactent le sol. L\'imperméabilisation par béton et asphalte interrompt définitivement le réseau souterrain. Le problème : les dégâts restent invisibles — il n\'existe actuellement aucun instrument documentant l\'état d\'un réseau mycorhizien avant et après une intervention.'],
  ['id'=>85,'lang'=>'fr','title'=>'Ce que la science sait — et ce qui reste ouvert','text'=>'Ce que nous savons avec certitude : les réseaux mycorhiziens sont présents chez plus de 90 % des plantes terrestres. Dans des conditions de stress, des études montrent des augmentations de rendement de 20 à 30 %. Le transport de nutriments et de carbone via les réseaux fongiques a été répliqué indépendamment plusieurs fois. Le mycélium fongique conduit des signaux électriques. Ce qui reste ouvert : la quantité réelle de CO₂ fixée par les réseaux mycorhiziens est étonnamment incertaine. Ce qui manque presque totalement : le bilan complet — mesurer simultanément CO₂, rendement, consommation d\'eau et santé des sols.'],
  ['id'=>86,'lang'=>'fr','title'=>'La technologie BioComm','text'=>'OpenMycoNet développe des nœuds de mesure abordables — BioComm Nodes — qui enregistrent les signaux bioélectriques dans le sol. Chaque nœud contient un microcontrôleur, plusieurs électrodes de mesure et une unité de stockage. Il est placé dans le sol, collecte des données en continu et les transmet périodiquement à un serveur central. Là, des patterns sont reconnus, des sites comparés, des changements documentés dans le temps. Toutes les données sont librement accessibles.'],
  ['id'=>87,'lang'=>'fr','title'=>'Pourquoi la science citoyenne — et pourquoi maintenant ?','text'=>'Les chercheurs professionnels peuvent mesurer un site, peut-être dix. Ce dont nous avons besoin, c\'est de cent sites — mille, sur des années. Aucune université ne peut y arriver seule. La technologie est aujourd\'hui abordable : un nœud de mesure complet coûte moins qu\'un bon dîner. Ce dont nous avons besoin, ce sont des personnes avec des jardins, des champs, des terrains boisés.'],
  ['id'=>88,'lang'=>'fr','title'=>'La vision à long terme d\'OpenMycoNet','text'=>'OpenMycoNet rêve d\'un réseau qui documente en permanence ce qui se passe sous nos pieds. Qui peut prouver quand une intervention endommage un réseau. Qui peut aider à faire reconnaître juridiquement les réseaux mycorhiziens pour ce qu\'ils sont biologiquement : des organismes vivants méritant protection. Chaque mesure nous rapproche d\'un pas. Le réseau est là. Nous apprenons tout juste à l\'écouter.'],
  ['id'=>89,'lang'=>'es','title'=>'Introducción — ¿Qué es OpenMycoNet?','text'=>'OpenMycoNet es un proyecto de ciencia ciudadana. Medimos las señales bioeléctricas de las redes fúngicas en el suelo — en tantos lugares como sea posible, durante el mayor tiempo posible. Lo que aprendemos, lo compartimos abiertamente. No somos un instituto de investigación. Lo que tenemos es curiosidad, algo de tecnología de medición y la convicción de que los ciudadanos pueden contribuir genuinamente a la ciencia — si se les dan las herramientas adecuadas.'],
  ['id'=>90,'lang'=>'es','title'=>'La red invisible bajo nuestros pies','text'=>'Directamente bajo nuestros pies, en cada paso por un bosque, se extiende una red de densidad inimaginable. Hilos más finos que un cabello humano — miles de millones de ellos en cada centímetro cúbico de tierra. Esta red vive, crece, reacciona, transporta, comunica. Y mantiene el bosque con vida desde hace cientos de millones de años.'],
  ['id'=>91,'lang'=>'es','title'=>'¿Qué es exactamente un hongo?','text'=>'Lo que percibimos como un hongo — el sombrero, el pie, la estructura que recogemos — no es el organismo en sí mismo. Es su órgano reproductor, su fruto. El hongo real vive escondido, bajo tierra, y suele ser muchas veces más grande de lo que alguna vez vemos. Los hongos forman su propio reino — los Fungi. No tienen clorofila y no pueden realizar la fotosíntesis. En cambio digieren fuera de su cuerpo secretando enzimas que descomponen la materia orgánica. Son los grandes descomponedores de la naturaleza — sin los cuales ningún bosque funcionaría.'],
  ['id'=>92,'lang'=>'es','title'=>'El micelio — el organismo real','text'=>'El cuerpo real de un hongo se llama micelio. Consiste en hilos muy finos — hifas — que se tejen a través de la tierra, la madera y las hojas. En un solo puñado de tierra forestal puede haber más hilos fúngicos que carreteras en una pequeña ciudad. El biólogo David Read calculó que la longitud total de todas las hifas fúngicas en las capas superiores del suelo supera muchas veces la distancia de la Tierra al Sol. El micelio no tiene cerebro ni sistema nervioso — y sin embargo se comporta de una manera que en un animal llamaríamos inteligente.'],
  ['id'=>93,'lang'=>'es','title'=>'Micorriza — la asociación más antigua del mundo','text'=>'Hace unos 450 millones de años, las primeras plantas se aventuraron desde el agua hacia la tierra firme — probablemente porque traían hongos como socios. Llamamos a esta conexión micorriza (griego: mykes = hongo, rhiza = raíz). El principio: la planta suministra al hongo azúcar — hasta el 30 % de su producción de glucosa. El hongo suministra a la planta agua y nutrientes profundamente en el suelo, especialmente fósforo. Las plantas con micorriza funcional crecen mejor, soportan mejor la sequía y necesitan menos fertilizante. Más del 90 % de todas las plantas terrestres forman asociaciones micorrícicas.'],
  ['id'=>94,'lang'=>'es','title'=>'La red forestal — conexiones entre árboles','text'=>'Las redes micorrícicas conectan las raíces de diferentes plantas. La ecóloga forestal Suzanne Simard demostró que el carbono — el azúcar — viaja realmente de los árboles grandes a las plantas más pequeñas: no por el aire, sino a través de la red fúngica en el suelo. Además del carbono, el nitrógeno, el fósforo y el agua también fluyen a través de la red. Estudios indican que ante el ataque de plagas, señales químicas pueden propagarse a través de la red hacia plantas vecinas.'],
  ['id'=>95,'lang'=>'es','title'=>'Señales eléctricas en redes fúngicas','text'=>'El micelio fúngico conduce señales eléctricas. Desde principios de los años noventa, Andrew Adamatzky en la Universidad del Oeste de Inglaterra estudia las propiedades electrofisiológicas de los hongos. Las señales siguen patrones — impulsos regulares que responden a estímulos externos. Adamatzky ha encontrado evidencias de que los hongos pueden producir hasta 50 patrones de señal diferentes. Si esto constituye una forma de procesamiento de información es una de las preguntas abiertas más apasionantes de la biología moderna. Esto es exactamente lo que impulsa a OpenMycoNet.'],
  ['id'=>96,'lang'=>'es','title'=>'Lo que amenaza las redes micorrícicas','text'=>'El arado profundo — método estándar de la agricultura convencional — corta físicamente las redes micorrícicas. Los fungicidas dañan los hongos micorrícicos. Los fertilizantes fosforados sintéticos hacen innecesaria la micorriza: los suelos muy fertilizados pierden su actividad micorrícica. La maquinaria pesada compacta el suelo. El sellado del suelo con hormigón y asfalto interrumpe permanentemente la red subterránea. El problema: el daño permanece invisible — actualmente no existe ningún instrumento que documente el estado de una red micorrícica antes y después de una intervención.'],
  ['id'=>97,'lang'=>'es','title'=>'Lo que la ciencia sabe — y lo que sigue abierto','text'=>'Lo que sabemos con bastante certeza: las redes micorrícicas están presentes en más del 90 % de todas las plantas terrestres. En condiciones de estrés, los estudios muestran aumentos de rendimiento del 20-30 %. El transporte de nutrientes y carbono a través de redes fúngicas ha sido replicado independientemente varias veces. El micelio fúngico conduce señales eléctricas. Lo que sigue abierto: cuánto CO₂ fijan realmente las redes micorrícicas es sorprendentemente incierto. Lo que casi falta por completo: el balance total — medir simultáneamente CO₂, rendimiento, consumo de agua y salud del suelo.'],
  ['id'=>98,'lang'=>'es','title'=>'La tecnología BioComm','text'=>'OpenMycoNet desarrolla nodos de medición asequibles — BioComm Nodes — que registran señales bioeléctricas en el suelo. Cada nodo contiene un microcontrolador, varios electrodos de medición y una unidad de almacenamiento. Se coloca en el suelo, recopila datos continuamente y los transmite periódicamente a un servidor central. Allí se reconocen patrones, se comparan ubicaciones, se documentan cambios a lo largo del tiempo. Todos los datos son de acceso libre.'],
  ['id'=>99,'lang'=>'es','title'=>'¿Por qué ciencia ciudadana — y por qué ahora?','text'=>'Los investigadores profesionales pueden medir un sitio, quizás diez. Lo que necesitamos son cien sitios — mil, durante años. Ninguna universidad puede hacerlo sola. La tecnología es hoy asequible: un nodo de medición completo cuesta menos que una buena cena. Lo que necesitamos son personas con jardines, campos, terrenos boscosos — dispuestas a colocar un pequeño dispositivo en el suelo.'],
  ['id'=>100,'lang'=>'es','title'=>'La visión a largo plazo de OpenMycoNet','text'=>'OpenMycoNet sueña con una red que documente permanentemente lo que ocurre bajo nuestros pies. Que pueda demostrar cuándo una intervención daña una red. Que pueda ayudar a que las redes micorrícicas sean reconocidas legalmente por lo que son biológicamente: organismos vivos dignos de protección. Cada medición nos acerca un paso más. La red está ahí. Solo estamos aprendiendo a escucharla.'],
  ['id'=>101,'lang'=>'de','title'=>'Kritische Perspektive: Was wirklich belegt ist','text'=>'Nicht alle populären Behauptungen über Mykorrhiza-Netzwerke sind wissenschaftlich gut belegt. Karst, Jones und Hoeksema (Nature Ecology & Evolution, 2023) analysieren, dass sich in der Literatur eine positive Zitationsbias entwickelt hat: Studien mit positiven Ergebnissen werden häufiger zitiert als solche mit gemischten oder negativen. Konkret bemängeln sie: Die Behauptung, dass Mykorrhiza-Netzwerke in Wäldern weit verbreitet sind, ist durch Feldstudien nicht ausreichend belegt. Der Ressourcentransfer zwischen Bäumen variiert stark und hat alternative Erklärungen. Die Idee dass Mutterbäume gezielt Ressourcen an Nachkommen senden, hat keine peer-reviewten Belege. Die Forscher fordern bessere Experimente und kritischeres Denken — sonst riskiere man, das \'Wood Wide Web\' in eine Fantasie zu verwandeln. OpenMycoNet teilt diese Haltung: Wir messen, weil die Datenlage noch dünn ist. Wir interpretieren Signale nicht vorschnell als Kommunikation.'],
  ['id'=>102,'lang'=>'en','title'=>'Critical perspective: What is actually proven','text'=>'Not all popular claims about mycorrhizal networks are well supported by science. Karst, Jones and Hoeksema (Nature Ecology & Evolution, 2023) found that a positive citation bias has developed in the literature: studies with positive results are cited far more often than those with mixed or negative findings. Specifically, they argue that the claim that mycorrhizal networks are widespread in forests is insufficiently supported by field studies; that resource transfer between trees varies widely and has alternative explanations; and that the idea of mother trees preferentially sending resources to offspring has no peer-reviewed published evidence. The researchers call for better experiments and more critical thinking — otherwise \'we risk turning the wood-wide web into a fantasy beneath our feet.\' OpenMycoNet shares this stance: we measure because the data is still thin. We do not prematurely interpret signals as communication.'],
  ['id'=>103,'lang'=>'nl','title'=>'Kritisch perspectief: Wat werkelijk bewezen is','text'=>'Niet alle populaire beweringen over mycorrhizanetwerken zijn wetenschappelijk goed onderbouwd. Karst, Jones en Hoeksema (Nature Ecology & Evolution, 2023) stellen dat er in de literatuur een positieve citatiebias is ontstaan. Concreet: de bewering dat mycorrhizanetwerken wijdverspreid zijn in bossen wordt onvoldoende ondersteund door veldstudies; de bewering dat moederbomen doelgericht hulpbronnen naar nakomelingen sturen heeft geen peer-reviewed bewijs. De onderzoekers roepen op tot betere experimenten en kritischer denken. OpenMycoNet deelt dit standpunt: we meten omdat de gegevens nog schaars zijn. We interpreteren signalen niet overhaast als communicatie.'],
  ['id'=>104,'lang'=>'fr','title'=>'Perspective critique : Ce qui est réellement prouvé','text'=>'Toutes les affirmations populaires sur les réseaux mycorhiziens ne sont pas bien étayées scientifiquement. Karst, Jones et Hoeksema (Nature Ecology & Evolution, 2023) ont constaté qu\'un biais de citation positif s\'est développé dans la littérature. Concrètement : l\'affirmation que les réseaux mycorhiziens sont répandus dans les forêts n\'est pas suffisamment soutenue par les études de terrain ; l\'idée que les arbres mères envoient préférentiellement des ressources à leurs descendants n\'a aucune preuve publiée et évaluée par des pairs. Les chercheurs appellent à de meilleures expériences et à une pensée plus critique — sinon \'on risque de transformer le wood-wide web en une fantaisie.\' OpenMycoNet partage cette position : nous mesurons parce que les données sont encore insuffisantes.'],
  ['id'=>105,'lang'=>'es','title'=>'Perspectiva crítica: Lo que realmente está probado','text'=>'No todas las afirmaciones populares sobre las redes micorrícicas están bien respaldadas por la ciencia. Karst, Jones y Hoeksema (Nature Ecology & Evolution, 2023) encontraron que se ha desarrollado un sesgo de citación positivo en la literatura. Concretamente: la afirmación de que las redes micorrícicas están ampliamente distribuidas en los bosques no está suficientemente respaldada por estudios de campo; la idea de que los árboles madre envían preferentemente recursos a su descendencia no tiene evidencia publicada con revisión por pares. Los investigadores piden mejores experimentos y pensamiento más crítico. OpenMycoNet comparte esta posición: medimos porque los datos aún son escasos. No interpretamos señales precipitadamente como comunicación.'],
  ['id'=>106,'lang'=>'de','title'=>'Rechtsform & Organisationsstruktur','text'=>'OpenMycoNet ist kein eingetragener Verein und keine gemeinnützige Organisation. Das Projekt wird von Robert Jank als unabhängigem Erfinder aus Maintal bei Frankfurt betrieben — ohne institutionelle Zugehörigkeit und ohne formelle Vereinsstruktur. Eine Formalisierung als Verein oder gemeinnützige Organisation ist langfristig denkbar, aktuell aber nicht vorhanden. Wer das Projekt unterstützen möchte, kann dies durch freiwillige Spenden tun.'],
  ['id'=>107,'lang'=>'en','title'=>'Legal structure & organisation','text'=>'OpenMycoNet is not a registered association and not a non-profit organisation. The project is run by Robert Jank as an independent inventor from Maintal near Frankfurt — without institutional affiliation and without a formal organisational structure. Formalisation as an association or non-profit is conceivable in the long term, but does not currently exist. Anyone wishing to support the project can do so through voluntary donations.'],
  ['id'=>108,'lang'=>'nl','title'=>'Rechtsvorm & organisatiestructuur','text'=>'OpenMycoNet is geen geregistreerde vereniging en geen non-profitorganisatie. Het project wordt gerund door Robert Jank als onafhankelijk uitvinder uit Maintal bij Frankfurt — zonder institutionele aansluiting en zonder formele organisatiestructuur. Formalisering als vereniging is op lange termijn denkbaar, maar bestaat momenteel niet. Wie het project wil steunen, kan dat doen via vrijwillige donaties.'],
  ['id'=>109,'lang'=>'fr','title'=>'Forme juridique & structure organisationnelle','text'=>'OpenMycoNet n\'est pas une association enregistrée et n\'est pas une organisation à but non lucratif. Le projet est géré par Robert Jank en tant qu\'inventeur indépendant de Maintal près de Francfort — sans affiliation institutionnelle et sans structure organisationnelle formelle. Une formalisation en association est envisageable à long terme, mais n\'existe pas actuellement. Toute personne souhaitant soutenir le projet peut le faire par des dons volontaires.'],
  ['id'=>110,'lang'=>'es','title'=>'Forma jurídica & estructura organizativa','text'=>'OpenMycoNet no es una asociación registrada ni una organización sin ánimo de lucro. El proyecto está gestionado por Robert Jank como inventor independiente de Maintal, cerca de Fráncfort — sin afiliación institucional y sin estructura organizativa formal. Una formalización como asociación es concebible a largo plazo, pero actualmente no existe. Quien desee apoyar el proyecto puede hacerlo mediante donaciones voluntarias.'],
  ['id'=>111,'lang'=>'de','title'=>'Kontakt & weitere Fragen','text'=>'Für Fragen die über diese Wissensbasis hinausgehen, oder für direkten Kontakt mit dem OpenMycoNet-Team, kannst du eine Email an kontakt@openmyconet.de schreiben. Robert Jank antwortet in der Regel innerhalb weniger Tage. Für Anmeldungen als Node-Operator oder Förderanfragen ist ebenfalls diese Adresse der richtige Weg.'],
  ['id'=>112,'lang'=>'en','title'=>'Contact & further questions','text'=>'For questions beyond this knowledge base, or for direct contact with the OpenMycoNet team, you can write an email to kontakt@openmyconet.de. Robert Jank usually responds within a few days. This address is also the right contact for node operator registrations or support enquiries.'],
  ['id'=>113,'lang'=>'nl','title'=>'Contact & verdere vragen','text'=>'Voor vragen die verder gaan dan deze kennisbank, of voor direct contact met het OpenMycoNet-team, kun je een e-mail sturen naar kontakt@openmyconet.de. Robert Jank reageert doorgaans binnen een paar dagen. Dit adres is ook de juiste weg voor aanmeldingen als knooppuntbeheerder of ondersteuningsverzoeken.'],
  ['id'=>114,'lang'=>'fr','title'=>'Contact & questions supplémentaires','text'=>'Pour les questions qui dépassent cette base de connaissances, ou pour un contact direct avec l\'équipe OpenMycoNet, vous pouvez écrire un email à kontakt@openmyconet.de. Robert Jank répond généralement dans quelques jours. Cette adresse est également la bonne voie pour les inscriptions en tant qu\'opérateur de nœud ou les demandes de soutien.'],
  ['id'=>116,'lang'=>'de','title'=>'Quellennachweise & wissenschaftliche Referenzen','text'=>'Alle wissenschaftlichen Quellen und Studien auf denen die Inhalte von OpenMycoNet basieren, sind auf der Seite Quellennachweise zusammengefasst. Diese findest du unter: https://www.openmyconet.de/quellennachweise.html — dort sind die zitierten Forschenden, Studien und Publikationen vollständig aufgeführt, darunter Arbeiten von Andrew Adamatzky, Suzanne Simard, David Read sowie Karst, Jones und Hoeksema (Nature Ecology & Evolution, 2023).'],
  ['id'=>117,'lang'=>'en','title'=>'References & scientific sources','text'=>'All scientific sources and studies on which OpenMycoNet content is based are listed on the References page. You can find it at: https://www.openmyconet.de/quellennachweise.html — there you will find the complete list of cited researchers, studies and publications, including work by Andrew Adamatzky, Suzanne Simard, David Read, and Karst, Jones and Hoeksema (Nature Ecology & Evolution, 2023).'],
  ['id'=>118,'lang'=>'nl','title'=>'Bronvermeldingen & wetenschappelijke referenties','text'=>'Alle wetenschappelijke bronnen waarop de inhoud van OpenMycoNet is gebaseerd, staan vermeld op de pagina Bronvermeldingen. Je vindt deze op: https://www.openmyconet.de/quellennachweise.html — daar staan de geciteerde onderzoekers, studies en publicaties volledig vermeld, waaronder werk van Andrew Adamatzky, Suzanne Simard, David Read en Karst, Jones en Hoeksema (Nature Ecology & Evolution, 2023).'],
  ['id'=>119,'lang'=>'fr','title'=>'Sources & références scientifiques','text'=>'Toutes les sources scientifiques sur lesquelles se basent les contenus d\'OpenMycoNet sont répertoriées sur la page Sources. Vous la trouverez à : https://www.openmyconet.de/quellennachweise.html — vous y trouverez la liste complète des chercheurs, études et publications cités, notamment les travaux d\'Andrew Adamatzky, Suzanne Simard, David Read et Karst, Jones et Hoeksema (Nature Ecology & Evolution, 2023).'],
  ['id'=>120,'lang'=>'es','title'=>'Fuentes & referencias científicas','text'=>'Todas las fuentes científicas en las que se basan los contenidos de OpenMycoNet están recogidas en la página de Fuentes. La encontrarás en: https://www.openmyconet.de/quellennachweise.html — allí encontrarás la lista completa de investigadores, estudios y publicaciones citados, incluyendo trabajos de Andrew Adamatzky, Suzanne Simard, David Read y Karst, Jones y Hoeksema (Nature Ecology & Evolution, 2023).'],
  ['id'=>115,'lang'=>'es','title'=>'Contacto & preguntas adicionales','text'=>'Para preguntas que van más allá de esta base de conocimiento, o para contacto directo con el equipo de OpenMycoNet, puedes escribir un correo a kontakt@openmyconet.de. Robert Jank suele responder en pocos días. Esta dirección también es el camino correcto para registros como operador de nodo o consultas de apoyo.'],

  // --- Förderer & Spenden ---
  ['id'=>121,'lang'=>'de','title'=>'Gewerbliche Förderer — Partnerschaft','text'=>'OpenMycoNet sucht gewerbliche Förderer die thematisch zum Projekt passen: Pilzzüchter, Buchhandlungen, Hersteller nachhaltiger Materialien, Agrartech-Unternehmen, Forstbetriebe und alle die das Thema Mykologie ernst nehmen. Als Förderer erhält man einen Eintrag in der Fördererliste auf openmyconet.de mit Name, Beschreibung, Kontaktdaten und Link, ein offizielles Förderer-Badge für die eigene Website, Nennung in relevanten E-Mails an die Community sowie thematische Sichtbarkeit im Kontext echter Citizen Science. Der Jahresbeitrag ist freiwillig und frei wählbar ab 50 € — alle Förderer erhalten dieselbe Sichtbarkeit unabhängig vom Betrag. Die Anfrage läuft über das Formular auf foerderer.html oder per E-Mail an kontakt@openmyconet.de. Nach der Anfrage prüft OpenMycoNet die thematische Passung innerhalb von 48 Stunden.'],
  ['id'=>122,'lang'=>'de','title'=>'Spenden — Projekt finanziell unterstützen','text'=>'OpenMycoNet ist ein unabhängiges Citizen-Science-Projekt ohne institutionelle Förderung. Serverkosten und Weiterentwicklung werden durch freiwillige Spenden finanziert. Spenden sind direkt über die Startseite möglich — per PayPal unter paypal.me/openmyconet. Man kann auch spenden ohne sich registrieren zu müssen, aber OpenMycoNet freut sich wenn Spender auch Teil des Netzwerks werden. Jeder Betrag hilft das Projekt am Leben zu halten.'],

  ['id'=>123,'lang'=>'en','title'=>'Commercial supporters — Partnership','text'=>'OpenMycoNet is looking for commercial supporters who fit thematically: mushroom growers, bookshops, manufacturers of sustainable materials, agri-tech companies, forestry businesses and anyone who takes the topic of mycology seriously. Supporters receive a listing in the supporter directory on openmyconet.de with name, description, contact details and link, an official supporter badge for their own website, mention in relevant community emails, and thematic visibility in the context of genuine citizen science. The annual contribution is voluntary and freely selectable from €50 — all supporters receive the same visibility regardless of the amount. Applications go through the form on foerderer.html or by email to kontakt@openmyconet.de.'],
  ['id'=>124,'lang'=>'en','title'=>'Donations — financially support the project','text'=>'OpenMycoNet is an independent citizen science project without institutional funding. Server costs and further development are financed by voluntary donations. Donations are possible directly via the homepage — via PayPal at paypal.me/openmyconet. You can donate without registering, but OpenMycoNet appreciates it when donors also become part of the network. Every contribution helps keep the project alive.'],

  ['id'=>125,'lang'=>'nl','title'=>'Commerciële supporters — Partnerschap','text'=>'OpenMycoNet zoekt commerciële supporters die thematisch bij het project passen: paddenstoelenkwekers, boekhandels, fabrikanten van duurzame materialen, agri-tech bedrijven, bosbouwbedrijven en iedereen die het onderwerp mycologie serieus neemt. Supporters ontvangen een vermelding in de supporterslijst op openmyconet.de, een officieel supportersbadge, vermelding in relevante community-e-mails en thematische zichtbaarheid. De jaarlijkse bijdrage is vrijwillig en vrij te kiezen vanaf €50 — alle supporters ontvangen dezelfde zichtbaarheid ongeacht het bedrag. Aanvragen via het formulier op foerderer.html of per e-mail aan kontakt@openmyconet.de.'],
  ['id'=>126,'lang'=>'nl','title'=>'Donaties — het project financieel steunen','text'=>'OpenMycoNet is een onafhankelijk citizen science-project zonder institutionele financiering. Serverkosten en verdere ontwikkeling worden gefinancierd door vrijwillige donaties via PayPal op paypal.me/openmyconet. Je kunt doneren zonder je te registreren, maar OpenMycoNet waardeert het als donateurs ook deel uitmaken van het netwerk. Elke bijdrage helpt het project in leven te houden.'],

  ['id'=>127,'lang'=>'fr','title'=>'Soutiens commerciaux — Partenariat','text'=>'OpenMycoNet recherche des soutiens commerciaux correspondant thématiquement au projet: producteurs de champignons, librairies, fabricants de matériaux durables, entreprises agri-tech, exploitations forestières et tous ceux qui prennent la mycologie au sérieux. Les soutiens reçoivent une inscription dans la liste des soutiens sur openmyconet.de, un badge officiel, une mention dans les e-mails communautaires et une visibilité thématique. La contribution annuelle est volontaire et librement choisissable à partir de 50 € — tous les soutiens reçoivent la même visibilité. Les demandes se font via le formulaire sur foerderer.html ou par e-mail à kontakt@openmyconet.de.'],
  ['id'=>128,'lang'=>'fr','title'=>'Dons — soutenir financièrement le projet','text'=>'OpenMycoNet est un projet de science citoyenne indépendant sans financement institutionnel. Les coûts de serveur et le développement sont financés par des dons volontaires via PayPal sur paypal.me/openmyconet. Il est possible de faire un don sans s\'inscrire, mais OpenMycoNet apprécie que les donateurs fassent également partie du réseau. Chaque contribution aide à maintenir le projet en vie.'],

  ['id'=>129,'lang'=>'es','title'=>'Patrocinadores comerciales — Asociación','text'=>'OpenMycoNet busca patrocinadores comerciales que encajen temáticamente: cultivadores de hongos, librerías, fabricantes de materiales sostenibles, empresas agri-tech, explotaciones forestales y todos los que se toman en serio la micología. Los patrocinadores reciben una entrada en la lista de patrocinadores en openmyconet.de, una insignia oficial, mención en los correos de la comunidad y visibilidad temática. La contribución anual es voluntaria y libremente seleccionable desde 50 € — todos los patrocinadores reciben la misma visibilidad. Las solicitudes se realizan a través del formulario en foerderer.html o por correo a kontakt@openmyconet.de.'],
  ['id'=>130,'lang'=>'es','title'=>'Donaciones — apoyar financieramente el proyecto','text'=>'OpenMycoNet es un proyecto de ciencia ciudadana independiente sin financiación institucional. Los costes de servidor y el desarrollo se financian con donaciones voluntarias a través de PayPal en paypal.me/openmyconet. Se puede donar sin registrarse, pero OpenMycoNet agradece que los donantes también formen parte de la red. Cada aportación ayuda a mantener el proyecto vivo.'],
];

// ---------------------------------------------------------------------------
// Spracherkennung
// ---------------------------------------------------------------------------
function detectLanguage(string $text): string {
    $t = mb_strtolower($text);
    $patterns = [
        'de' => '/\b(ist|sind|was|wie|wann|kann|ich|das|die|der|ein|und|für|gibt|werden|haben|welche|knoten|gerät|mitmachen|verfügbar|zeitplan|spenden|datenschutz|pilz|mykorrhiza)\b/',
        'en' => '/\b(is|are|what|when|how|can|the|and|for|does|will|have|which|node|device|join|available|timeline|donate|privacy|fungal|mycorrhiza)\b/',
        'nl' => '/\b(is|zijn|wat|hoe|wanneer|kan|het|de|en|voor|heeft|welke|knooppunt|meedoen|beschikbaar|doneren)\b/',
        'fr' => '/\b(est|sont|quoi|comment|quand|peut|le|la|les|et|pour|avez|quel|nœud|disponible|donner|champignon)\b/',
        'es' => '/\b(es|son|qué|cómo|cuándo|puede|el|la|los|y|para|tiene|cuál|nodo|disponible|donar|hongo)\b/',
    ];
    $scores = [];
    foreach ($patterns as $lang => $pat) {
        preg_match_all($pat, $t, $m);
        $scores[$lang] = count($m[0]);
    }
    arsort($scores);
    $best = array_key_first($scores);
    return ($scores[$best] > 0) ? $best : 'de';
}

// ---------------------------------------------------------------------------
// Chunk-Retrieval
// ---------------------------------------------------------------------------
function findChunks(string $query, string $lang, array $chunks, int $topK = 3): array {
    $words = array_filter(explode(' ', mb_strtolower($query)), fn($w) => mb_strlen($w) > 3);

    $synonyms = [
        'verfügbar' => ['hardware','zeitplan','verfügbar','gerät','knoten','pcb','prototyp'],
        'gerät'     => ['hardware','zeitplan','verfügbar','gerät','knoten','pcb','prototyp'],
        'available' => ['hardware','timeline','available','device','node','pcb','prototype'],
        'mitmachen' => ['mitmachen','knoten','hardware','schritt','elektrode','betreiben'],
        'join'      => ['join','node','hardware','step','electrode','operate'],
        'datenschutz' => ['datenschutz','gps','daten','privat','anonym'],
        'privacy'   => ['privacy','gps','data','personal','anonymous'],
        'spenden'   => ['spenden','unterstütz','förder','förderer','paypal','finanzier','beitrag','jahresbeitrag'],
        'donate'    => ['donate','support','fund','sponsor','paypal','contribution','partner'],
        'fördern'   => ['förder','förderer','partner','unterstütz','gewerblich','jahresbeitrag','beitrag','badge'],
        'förderer'  => ['förder','förderer','partner','unterstütz','gewerblich','jahresbeitrag','beitrag','badge'],
        'sponsor'   => ['förder','förderer','partner','unterstütz','gewerblich','sponsor'],
        'unterstütz'=> ['spenden','förder','förderer','paypal','unterstütz','partner','beitrag'],
        'disponible'=> ['hardware','calendrier','nœud','nodo'],
        'beschikbaar'=> ['hardware','tijdlijn','knooppunt'],
    ];

    $expanded = array_values($words);
    foreach ($words as $w) {
        foreach ($synonyms as $key => $syns) {
            if (str_contains($w, $key) || str_contains($key, $w)) {
                $expanded = array_merge($expanded, $syns);
            }
        }
    }

    $langChunks = array_filter($chunks, fn($c) => $c['lang'] === $lang);
    $scored = [];
    foreach ($langChunks as $c) {
        $haystack = mb_strtolower($c['text'] . ' ' . $c['title']);
        $score = 0;
        foreach ($expanded as $w) {
            if (str_contains($haystack, $w)) $score++;
        }
        $scored[] = ['score' => $score, 'chunk' => $c];
    }
    usort($scored, fn($a, $b) => $b['score'] - $a['score']);

    $best = array_filter($scored, fn($s) => $s['score'] > 0);
    $result = array_slice(array_column(array_values($best ?: $scored), 'chunk'), 0, $topK);
    return $result;
}

// ---------------------------------------------------------------------------
// System-Prompts
// ---------------------------------------------------------------------------
$systemPrompts = [
    'de' => "Du bist der offizielle Assistent von OpenMycoNet, einem Citizen-Science-Projekt zur Messung bioelektrischer Signale in Mykorrhiza- und Pilznetzwerken.

Beantworte Fragen ausschließlich auf Basis des folgenden Kontexts. Erfinde keine Informationen.

Halte dich bei deinen Antworten an diese Evidenzhierarchie — ohne sie dem Nutzer immer explizit zu nennen, aber lass sie deine Formulierungen leiten:
- Gesichert (peer-reviewed, mehrfach repliziert): klar und direkt formulieren
- Aktuelle Forschung (Adamatzky et al., neuere Studien): \"Studien zeigen...\", \"Forschende beobachten...\"
- OpenMycoNet-Hypothese (Mustererkennung, KI-Analyse): \"OpenMycoNet untersucht...\", \"wir vermuten...\"
- Vision (langfristige Ziele): \"Das langfristige Ziel ist...\", \"wir hoffen...\"

Wichtig: OpenMycoNet interpretiert Signale nicht vorschnell als Kommunikation oder Sprache — wir untersuchen Muster, Reaktionen und Korrelationen. Formuliere entsprechend vorsichtig wenn es um die Interpretation von Messdaten geht.

Antworte gesprächig und direkt — kein unnötiger Formalismus. Wenn etwas noch in Entwicklung ist oder noch nicht bekannt, sag es ehrlich. Erfinde niemals Angaben zur Rechtsform, Vereinsstruktur oder Gemeinnützigkeit — wenn der Kontext dazu nichts enthält, antworte mit 'Dazu habe ich keine Information.' Wenn du eine Frage gar nicht beantworten kannst, weise freundlich auf kontakt@openmyconet.de hin. Antworte auf Deutsch.

Kontext:\n\n",

    'en' => "You are the official assistant of OpenMycoNet, a citizen science project measuring bioelectrical signals in mycorrhizal and fungal networks.

Answer questions only based on the context below. Do not invent information.

Follow this evidence hierarchy in your wording — without always explicitly labelling it, but let it guide your formulations:
- Established (peer-reviewed, replicated): state clearly and directly
- Current research (Adamatzky et al., recent studies): 'Studies show...', 'Researchers observe...'
- OpenMycoNet hypothesis (pattern recognition, AI analysis): 'OpenMycoNet investigates...', 'we suspect...'
- Vision (long-term goals): 'The long-term goal is...', 'we hope...'

Important: OpenMycoNet does not prematurely interpret signals as communication or language — we investigate patterns, reactions and correlations. Formulate carefully when it comes to interpreting measurement data.

Answer in a conversational, direct tone — no unnecessary formalism. Be honest when something is still in development or unknown. Never invent details about legal structure, association status or non-profit status — if the context contains nothing on this, say 'I don't have information on that.' If you cannot answer a question at all, kindly point to kontakt@openmyconet.de. Answer in English.

Context:\n\n",

    'nl' => "Je bent de officiële assistent van OpenMycoNet, een citizen science-project dat bio-elektrische signalen in mycorrhiza- en schimmelnetwerken meet.

Beantwoord vragen uitsluitend op basis van de onderstaande context. Verzin geen informatie.

Volg deze bewijshiërarchie in je formuleringen — zonder die altijd expliciet te benoemen:
- Vastgesteld (peer-reviewed, gerepliceerd): duidelijk en direct formuleren
- Actueel onderzoek: 'Studies tonen aan...', 'Onderzoekers observeren...'
- OpenMycoNet-hypothese: 'OpenMycoNet onderzoekt...', 'we vermoeden...'
- Visie: 'Het langetermijndoel is...', 'we hopen...'

Belangrijk: OpenMycoNet interpreteert signalen niet overhaast als communicatie — we onderzoeken patronen, reacties en correlaties. Wees eerlijk als iets nog in ontwikkeling is. Verzin nooit details over rechtsvorm of verenigingsstatus — als de context daar niets over bevat, zeg dan 'Daar heb ik geen informatie over.' Als je een vraag helemaal niet kunt beantwoorden, verwijs dan vriendelijk naar kontakt@openmyconet.de. Antwoord in het Nederlands.

Context:\n\n",

    'fr' => "Tu es l'assistant officiel d'OpenMycoNet, un projet de science citoyenne mesurant les signaux bioélectriques dans les réseaux mycorhiziens et fongiques.

Réponds aux questions uniquement sur la base du contexte ci-dessous. N'invente pas d'informations.

Suis cette hiérarchie de preuves dans tes formulations — sans toujours l'étiqueter explicitement :
- Établi (peer-reviewed, répliqué) : formuler clairement et directement
- Recherche actuelle : 'Les études montrent...', 'Les chercheurs observent...'
- Hypothèse OpenMycoNet : 'OpenMycoNet étudie...', 'nous supposons...'
- Vision : 'L'objectif à long terme est...', 'nous espérons...'

Important : OpenMycoNet n'interprète pas prématurément les signaux comme une communication — nous étudions des patterns, des réactions et des corrélations. Sois honnête si quelque chose est encore en développement. N'invente jamais de détails sur la forme juridique ou le statut associatif — si le contexte ne contient rien à ce sujet, dis 'Je n'ai pas d'information à ce sujet.' Si tu ne peux pas répondre à une question du tout, indique gentiment kontakt@openmyconet.de. Réponds en français.

Contexte:\n\n",

    'es' => "Eres el asistente oficial de OpenMycoNet, un proyecto de ciencia ciudadana que mide señales bioeléctricas en redes micorrícicas y fúngicas.

Responde preguntas únicamente basándote en el contexto siguiente. No inventes información.

Sigue esta jerarquía de evidencia en tus formulaciones — sin etiquetarla siempre explícitamente:
- Establecido (revisado por pares, replicado): formular clara y directamente
- Investigación actual: 'Los estudios muestran...', 'Los investigadores observan...'
- Hipótesis de OpenMycoNet: 'OpenMycoNet investiga...', 'sospechamos...'
- Visión: 'El objetivo a largo plazo es...', 'esperamos...'

Importante: OpenMycoNet no interpreta señales prematuramente como comunicación — investigamos patrones, reacciones y correlaciones. Sé honesto si algo está aún en desarrollo. Nunca inventes detalles sobre la forma jurídica o el estatus de asociación — si el contexto no contiene nada al respecto, di 'No tengo información sobre eso.' Si no puedes responder una pregunta en absoluto, indica amablemente kontakt@openmyconet.de. Responde en español.

Contexto:\n\n",
];

// ---------------------------------------------------------------------------
// Retrieval + API-Call
// ---------------------------------------------------------------------------
$lang = detectLanguage($message);
$selectedChunks = findChunks($message, $lang, $chunks);
$context = implode("\n\n", array_map(fn($c) => "[{$c['title']}]\n{$c['text']}", $selectedChunks));
$chunkTitles = array_column($selectedChunks, 'title');
$system = ($systemPrompts[$lang] ?? $systemPrompts['de']) . $context;

// Gesprächsverlauf bereinigen (max. 10 Turns)
$cleanHistory = [];
foreach (array_slice($history, -10) as $m) {
    if (in_array($m['role'] ?? '', ['user', 'assistant']) && !empty($m['content'])) {
        $cleanHistory[] = ['role' => $m['role'], 'content' => $m['content']];
    }
}
$cleanHistory[] = ['role' => 'user', 'content' => $message];

$payload = json_encode([
    'model'      => 'claude-sonnet-4-6',
    'max_tokens' => 1000,
    'system'     => $system,
    'messages'   => $cleanHistory,
], JSON_UNESCAPED_UNICODE);

$ch = curl_init('https://api.anthropic.com/v1/messages');
curl_setopt_array($ch, [
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_POST           => true,
    CURLOPT_POSTFIELDS     => $payload,
    CURLOPT_HTTPHEADER     => [
        'Content-Type: application/json',
        'anthropic-version: 2023-06-01',
        'x-api-key: ' . ANTHROPIC_API_KEY,
    ],
    CURLOPT_TIMEOUT        => 30,
]);

$response = curl_exec($ch);
$httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
curl_close($ch);

if (!$response) {
    http_response_code(502);
    echo json_encode(['error' => 'API nicht erreichbar']);
    exit;
}

$data = json_decode($response, true);

if ($httpCode !== 200 || empty($data['content'][0]['text'])) {
    http_response_code(502);
    echo json_encode(['error' => $data['error']['message'] ?? 'Unbekannter API-Fehler']);
    exit;
}

echo json_encode([
    'answer'      => $data['content'][0]['text'],
    'chunks_used' => $chunkTitles,
    'lang'        => $lang,
], JSON_UNESCAPED_UNICODE);
